### ISSUE TITLE
RestartThenRepairNode failed after machine restarted with new public IP

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla-cluster-tests#2854] opened 2020-11-10 10:30 UTC
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on]
* **scylla**: [branch or commit hash]

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip]

### Description
test_id=c9e45a15-5d64-4aad-a82c-73c773d2def2
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/c9e45a15-5d64-4aad-a82c-73c773d2def2/20201109_183450/db-cluster-c9e45a15.zip
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/c9e45a15-5d64-4aad-a82c-73c773d2def2/20201109_183450/loader-set-c9e45a15.zip
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/c9e45a15-5d64-4aad-a82c-73c773d2def2/20201109_183450/monitor-set-c9e45a15.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/c9e45a15-5d64-4aad-a82c-73c773d2def2/20201109_183450/sct-runner-c9e45a15.zip
RestartThenRepairNode failed after machine restarted with new public IP.
SCT does not handle this IP change and node fail to restart.
(DisruptionEvent Severity.ERROR): type=end name=RestartThenRepairNode

**from hydra report :**
longevity-counters-multidc-4-3-db-node-c9e45a15-10 | 34.220.156.55 | running | aws | us-west-2

**from sct events the IP is not updated with new IP.**

2020-11-09 17:58:25.653: (DisruptionEvent Severity.ERROR): type=end name=RestartThenRepairNode node=Node longevity-counters-multidc-4-3-db-node-c9e45a15-10 [54.191.59.140 | 10.0.3.29] (seed: False) duration=330 error=timed out

-- | -- | -- | -- | --

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
restart node 
2. [Second Step]

3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by fgelcer** [comment] 2020-11-10 10:32
this happens on branch-4.3

**Comment by roydahan** [comment] 2020-11-10 10:35
@bentsi / @dkropachev, AFAIU from @fruch it's something that has broken since we moved to the new SSH.
How hard to fix?

**Comment by fruch** [comment] 2020-11-10 10:42
> @bentsi / @dkropachev, AFAIU from @fruch it's something that has broken since we moved to the new SSH.
> How hard to fix?

I don't it's very hard,
4f8ee2d7bf9adac7746228826a54f41075b58e2b introduced a new function `None.refresh_ip_address()` the new implementations of different ssh class should support it, and stop any ongoing connections, and reopen them. (the old implementation was doing it automaticly on case of errors, and opening a new connection each time a run command was called)

just saying it's something easy to miss, and we are missing it for the second or third time...

**Comment by juliayakovlev** [comment] 2023-07-10 05:56
@fruch looks like the issue is fixed. We can close the issue

**Comment by fruch** [comment] 2023-07-10 07:39
fixed in https://github.com/scylladb/scylla-cluster-tests/pull/2880

**Closed by fruch** 2023-07-10 07:39 UTC
Labels: no-issue-activity
