### ISSUE TITLE
[Azure] cloud-init timeout on waiting for status

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6649] opened 2023-10-03 12:17 UTC
## Issue description

- [X] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

```
2023-10-02 16:06:04.313: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=d0fa2ba1-d4d1-49fb-82ff-3a29eee22002, source=LongevityTest.SetUp()
exception=Failed to run a command due to exception!
Command: 'sudo cloud-init status --wait'
Stdout:
Stderr:
Exception:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 588, in run
self.connect()
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 524, in connect
raise ConnectTimeout(ex_msg) from exc
Failed to connect in 60 seconds, last error: (ConnectError)Error connecting to host '20.115.98.228:22' - timed out
```

## Impact

we can't run longvities

## How frequently does it reproduce?

happen multiple time on this job

## Installation details

Cluster size: 4 nodes (Standard_L16s_v3)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCYLLA-IMAGES/providers/Microsoft.Compute/images/scylla-5.4.0-dev-x86_64-2023-10-02T07-37-15` (azure: undefined_region)

Test: `longevity-1tb-5days-azure-test`
Test id: `18997e53-cf08-4b6b-806c-a1f82aa3a501`
Test name: `scylla-master/longevity/longevity-1tb-5days-azure-test`
Test config file(s):

- [longevity-1TB-5days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5f82c91f45055e4c79cff76480821f3b09da535b/test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 18997e53-cf08-4b6b-806c-a1f82aa3a501`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=18997e53-cf08-4b6b-806c-a1f82aa3a501)
- Show all stored logs command: `$ hydra investigate show-logs 18997e53-cf08-4b6b-806c-a1f82aa3a501`

## Logs:
- **db-cluster-18997e53.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18997e53-cf08-4b6b-806c-a1f82aa3a501/20231002_160624/db-cluster-18997e53.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18997e53-cf08-4b6b-806c-a1f82aa3a501/20231002_160624/db-cluster-18997e53.tar.gz)
- **sct-runner-events-18997e53.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18997e53-cf08-4b6b-806c-a1f82aa3a501/20231002_160624/sct-runner-events-18997e53.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18997e53-cf08-4b6b-806c-a1f82aa3a501/20231002_160624/sct-runner-events-18997e53.tar.gz)
- **sct-18997e53.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18997e53-cf08-4b6b-806c-a1f82aa3a501/20231002_160624/sct-18997e53.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18997e53-cf08-4b6b-806c-a1f82aa3a501/20231002_160624/sct-18997e53.log.tar.gz)
- **loader-set-18997e53.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18997e53-cf08-4b6b-806c-a1f82aa3a501/20231002_160624/loader-set-18997e53.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18997e53-cf08-4b6b-806c-a1f82aa3a501/20231002_160624/loader-set-18997e53.tar.gz)
- **monitor-set-18997e53.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18997e53-cf08-4b6b-806c-a1f82aa3a501/20231002_160624/monitor-set-18997e53.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18997e53-cf08-4b6b-806c-a1f82aa3a501/20231002_160624/monitor-set-18997e53.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-1tb-5days-azure-test/17/)
[Argus](https://argus.scylladb.com/test/d03f9d55-942a-4f66-ae48-9d35d59a59e2/runs?additionalRuns[]=18997e53-cf08-4b6b-806c-a1f82aa3a501)
</details>

**Comment by fruch** [comment] 2023-10-03 12:19
I suspect or 
https://github.com/scylladb/scylla-cluster-tests/pull/6643

or 

https://github.com/scylladb/scylla-machine-image/pull/445, but it was reverted, so it's not clear...

we'll need to manually investigate this one

**Comment by soyacz** [comment] 2023-10-04 08:05
I tried to reproduce it twice and failed - everything looks ok.
For me it looks like some Azure issue - as first VM was OK, it freezes on the second db node and even ssh didn't work (which should work out of the box)

I try another one to make sure it passes.

**Comment by soyacz** [comment] 2023-10-04 08:26
ok, I got reproduction when trying 'on_demand' instance (az: c, I don't know if it matters)

**Comment by soyacz** [comment] 2023-10-04 08:57
VM hangs in `"provisioningState": "Creating",` state

**Comment by soyacz** [comment] 2023-10-04 11:49
This happened randomly. What I found, that OS disks for db nodes were HDD kind. Possibly this was causing some problems with VM startup.
The reason of this was that job was set to private @aleksbykov branch called `azure-increase-sct-runner-disk` which possibly was breaking disk setup.
I fixed job configuration. Closing until reproduction.

**Closed by soyacz** 2023-10-04 11:49 UTC
Labels: Azure

**Comment by fruch** [comment] 2023-10-04 12:48
@soyacz I've rerun the job, and lets see how it works.

**Comment by fruch** [comment] 2023-10-04 12:49
so far so good:

https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-1tb-5days-azure-test/18/

it's passed that point, and it's in db cluster configuration now
