### ISSUE TITLE
hydra-show-monitor job should use spot. It's stuck on Waiting for next available executor on ‘aws-eu-west-1-qa-builder-v2-1-CI i-0e73a4d099a3de78f

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#7648] opened 2024-06-13 09:05 UTC
```
00:00:00.004  Started by user [Yaniv Kaul](https://jenkins.scylladb.com/user/mykaul)
00:00:06.453  Obtained jenkins-pipelines/qa/hydra-show-monitor.jenkinsfile from git git@github.com:scylladb/scylla-cluster-tests.git
00:00:06.667  [Pipeline] Start of Pipeline
00:00:06.707  [Pipeline] library
00:00:06.715  Loading library sct@snapshot
00:00:06.717  The recommended git tool is: git
00:00:06.717  using credential b8a774da-0e46-4c91-9f74-09caebaea261
00:00:06.809   > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/QA-tools/jobs/hydra-show-monitor/workspace@libs/969d6f8d4eaf63f251754863f75ad533b217fe45c16c86ac8ef14c428b1a3112/.git # timeout=10
00:00:06.824  Fetching changes from the remote Git repository
00:00:06.826   > git config remote.origin.url git@github.com:scylladb/scylla-cluster-tests.git # timeout=10
00:00:06.836  Fetching upstream changes from git@github.com:scylladb/scylla-cluster-tests.git
00:00:06.836   > git --version # timeout=10
00:00:06.849   > git --version # 'git version 2.25.1'
00:00:06.849  using GIT_SSH to set credentials New RSA key for slaves
00:00:06.884   > git fetch --tags --force --progress -- git@github.com:scylladb/scylla-cluster-tests.git +refs/heads/*:refs/remotes/origin/* # timeout=10
00:00:10.919   > git rev-parse origin/master^{commit} # timeout=10
00:00:10.944  Checking out Revision ef159f51300dcee27f8840519da803dabe1d54ef (origin/master)
00:00:10.944   > git config core.sparsecheckout # timeout=10
00:00:10.973   > git checkout -f ef159f51300dcee27f8840519da803dabe1d54ef # timeout=10
00:00:11.086  Commit message: "improvement(k8s): allow to configure base K8S version via jenkins"
00:00:11.089   > git rev-list --no-walk ef159f51300dcee27f8840519da803dabe1d54ef # timeout=10
00:00:12.176  [Pipeline] node
00:00:27.195  Still waiting to schedule task
00:00:27.195  Waiting for next available executor on ‘[aws-eu-west-1-qa-builder-v2-1-CI i-0e73a4d099a3de78f](https://jenkins.scylladb.com/computer/i%2D0e73a4d099a3de78f/)’
```

**Comment by fruch** [comment] 2024-06-13 09:07
@mykaul 

I zero clue, what is the issue here.

this does use spot, and I don't understand what's not working, also a link would be helpful to under a bit better.

what seen in this log, is this job is waiting for a worker, that can take a few minutes to be available.

**Comment by mykaul** [comment] 2024-06-13 10:10
> @mykaul
> 
> I zero clue, what is the issue here.
> 
> this does use spot, and I don't understand what's not working, also a link would be helpful to under a bit better.
> 
> what seen in this log, is this job is waiting for a worker, that can take a few minutes to be available.

Is it waiting for the spot to become available?

**Comment by mykaul** [comment] 2024-06-13 10:40
https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/794/console is the link.

**Comment by mykaul** [comment] 2024-06-13 11:37
(for some reason it pulls hydra twice, and each pull is ~1m)

**Comment by mykaul** [comment] 2024-06-13 11:39
It wasn't stuck for ages, so I'll close it now. I had expected it to be up and running faster.

**Closed by mykaul** 2024-06-13 11:39 UTC

**Comment by fruch** [comment] 2024-06-13 11:46
> (for some reason it pulls hydra twice, and each pull is ~1m)

it's by design

one time to run the code that create an sct-runner, and one time to run the `hydra investigate show-monitor` command on that runner.
