### ISSUE TITLE
random error about scylla version

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-cluster-tests#7156] opened 2024-01-27 19:53 UTC
### Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

```
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/performance_regression_test.py", line 627, in test_latency_mixed_with_nemesis
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.preload_data()
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/performance_regression_test.py", line 246, in preload_data
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     stress_queue.append(self.run_stress_thread(**params))
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1813, in run_stress_thread
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return self.run_stress_cassandra_thread(**params)
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1849, in run_stress_cassandra_thread
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     cs_thread = CassandraStressThread(loader_set=self.loaders,
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 92, in __init__
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     super().__init__(loader_set=loader_set, stress_cmd=stress_cmd, timeout=timeout,
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/stress/base.py", line 48, in __init__
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     if "k8s" not in self.params.get("cluster_backend") and self.docker_image_name:
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     val = self.func(instance)
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 203, in docker_image_name
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return get_docker_image_by_version(self.node_list[0].get_scylla_binary_version())
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/version_utils.py", line 342, in get_docker_image_by_version
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     short_scylla_version = SCYLLA_VERSION_RE.match(scylla_version)
21:52:09  < t:2024-01-27 19:52:08,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > TypeError: expected string or bytes-like object
```

**Comment by fruch** [comment] 2024-07-25 05:26
`get_docker_image_by_version` function is gone, so this specific one won't be happening again.

the root cause of `update_db_package` broken was addressed on it's own.

so given all that, closing this one

**Closed by fruch** 2024-07-25 05:26 UTC
