### ISSUE TITLE
Ubuntu 18.04 rolling upgrade fails: Monitor setup fails

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#1788] opened 2020-02-09 10:13 UTC
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: f4f8efef43834812e445901c79e47aa8ab5640ae

### Logs
* test_id: 7b8b46e1-25d2-4a8b-8dbe-8ee223cbe427
* job log: https://jenkins.scylladb.com/view/master/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ubuntu18.04/11

### Description

In the monitor setup, (about an hour) after executing `sudo systemctl restart docker` sct lost connection to the monitor server for no apparent reason.

### Steps to Reproduce

1. Start a scylla cluster test rolling upgrade
2. Wait for the monitor setup

**Expected behavior:** The monitor setup finishes successfully

**Actual behavior:** The setup fails

**Comment by fruch** [comment] 2023-07-27 06:12
duplicate of #2217

**Closed** 2023-07-27 06:12 UTC
Labels: no-issue-activity
