### ISSUE TITLE
The 4days run finished earlier because all stress commands return code 137 (SIGKILL'ed)

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla-cluster-tests#6306] opened 2023-06-28 14:56 UTC
The run finished earlier because of out of memory: stress command return code is 137 which means 'out of memory' but loaders have enough memory to run cassandra-stress (16GB) and OS metrics show that there are a lot of free memory. And I don't see any limits we set for Docker containers too. 

So, the main suspect is SCT runner itself, but unfortunately we don't collect OS metrics for it. 

This happens on all 3 loaders for all stress commands (read, mixed, and user) For long-term running jobs we use r5.large instance type which has 16GB of RAM.

Available memory on loaders side:

![image](https://github.com/scylladb/scylla-cluster-tests/assets/63434/54b31417-000e-4f39-b9e3-936ebee5d6b6)

Run: https://argus.scylladb.com/test/ba476610-1983-41d1-8d84-420d0d44ba8d/runs?additionalRuns%5B%5D=2fdd4b8a-140a-4c77-8b5b-3e794a53f7e1

```
stress_cmd=cassandra-stress user profile=/tmp/cs_mv_profile.yaml ops'(insert=3,read1=1,read2=1,read3=1)' cl=QUORUM duration=4320m -mode cql3 native -rate threads=20
errors:
Stress command completed with bad status 137
```

**Comment by enaydanov** [comment] 2023-06-29 11:07
Maybe I was wrong about return code 137 because:

```
137 = killed by SIGKILL

Exit code 137 is Linux-specific and means that your process was killed by a signal, namely SIGKILL . The main reason for a process getting killed by SIGKILL on Linux (unless you do it yourself) is running out of memory.
```

**Comment by fruch** [comment] 2023-06-29 13:44
The trick is to find the action\event started the test shutdown.

It might be that we have some issues that make it unclear, and we should fix them.

But the first order of business is to find the cause, and if it's a core issue or not

**Comment by enaydanov** [comment] 2023-06-30 04:51
Looks like Alex and I found the root of cause: disrupt_remove_node_then_add_node failed to add a new node because  node-2 added itself back to the raft group after hard reboot during disrupt_decommission_streaming_err earlier. See https://github.com/scylladb/scylla-cluster-tests/issues/6140 for details.

**Comment by roydahan** [comment] 2023-07-02 16:23
I assume we can close this one.

**Closed by roydahan** 2023-07-02 16:23 UTC
