### ISSUE TITLE
SCYLLA_VERSION_RE.match(scylla_version) should have a fallback if it doesn't find the scylla version and not to be run when using prepared loaders

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-cluster-tests#7162] opened 2024-01-27 20:46 UTC
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/avi/job/avi-regression-latency-650gb-grow-shrink/8/console

It takes about 25 minutes to do some setup, then decide it's not working.

```
22:08:56  Started by user [Avi Kivity](https://jenkins.scylladb.com/user/avikivity)
```

```
22:43:54  < t:2024-01-27 20:43:53,792 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-01-27 20:43:53.791: (InfoEvent Severity.NORMAL) period_type=not-set event_id=565d49e0-7939-490f-88ae-d56e99e7ef13: message=TEST_END
```

**Comment by roydahan** [comment] 2024-03-04 16:22
First, I created a separate "epic" task to optimize test setup time (#7242 ).

In this case, the issue is that SCT couldn't detect the provided scylla version, probably it was a private build with non-matching pattern of scylla version.

The expectation should be a fallback to choose a loader from master.

File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/version_utils.py", line 342, in get_docker_image_by_version
22:52:46  short_scylla_version = SCYLLA_VERSION_RE.match(scylla_version)

Another optimization we should do is not doing this docker loading at all when using "use_prepared_loaders: true"

**Comment by fruch** [comment] 2024-07-23 10:13
we don't have the function of selecting a docker image, so we can close this one

**Closed by fruch** 2024-07-23 10:13 UTC
