### ISSUE TITLE
wait_db_up(timeout=500) only wait 97 seconds and raise timeout exception

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#2192] opened 2020-05-27 11:00 UTC
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-4.0
scylla version: 4.0.1

### Logs
* test_id: 5a671aa8-fbca-4b97-a913-9fcf2d2eb416
* job: https://jenkins.scylladb.com/view/scylla-4.0/job/scylla-4.0/job/rolling-upgrade/job/rolling-upgrade-debian9-test/46/consoleFull
* job log: 
```
$ hydra investigate show-logs 5a671aa8-fbca-4b97-a913-9fcf2d2eb416
prometheus  | https://cloudius-jenkins-test.s3.amazonaws.com/5a671aa8-fbca-4b97-a913-9fcf2d2eb416/prometheus_snapshot_20200525_021655.tar.gz
grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/5a671aa8-fbca-4b97-a913-9fcf2d2eb416/20200525_020924/grafana-screenshot-overview-20200525_021322-rolling-upgrade-4-0-debian-stretch-monitor-node-5a671aa8-0-1.png
grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/5a671aa8-fbca-4b97-a913-9fcf2d2eb416/20200525_020924/grafana-screenshot-scylla-per-server-metrics-nemesis-20200525_020925-rolling-upgrade-4-0-debian-stretch-monitor-node-5a671aa8-0-1.png
grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/5a671aa8-fbca-4b97-a913-9fcf2d2eb416/20200525_021702/grafana-screenshot-overview-20200525_022013-rolling-upgrade-4-0-debian-stretch-monitor-node-5a671aa8-0-1.png
grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/5a671aa8-fbca-4b97-a913-9fcf2d2eb416/20200525_021702/grafana-screenshot-scylla-per-server-metrics-nemesis-20200525_021703-rolling-upgrade-4-0-debian-stretch-monitor-node-5a671aa8-0-1.png
db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/5a671aa8-fbca-4b97-a913-9fcf2d2eb416/20200525_022400/db-cluster-5a671aa8.zip
loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/5a671aa8-fbca-4b97-a913-9fcf2d2eb416/20200525_022400/loader-set-5a671aa8.zip
monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/5a671aa8-fbca-4b97-a913-9fcf2d2eb416/20200525_022400/monitor-set-5a671aa8.zip
sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/5a671aa8-fbca-4b97-a913-9fcf2d2eb416/20200525_022400/sct-runner-5a671aa8.zip
```
### Description

After upgraded first node, the test wait for 500 second until the db is up.
in this job, a timeout exception raised, but it actually only wait for 97 seconds.

### Steps to Reproduce

1.

**Expected behavior:** [What you expected to happen]

wait for 500 second

**Actual behavior:** [What actually happened]

```
2020-05-25T01:46:10+00:00  rolling-upgrade-4-0-debian-stretch-db-node-5a671aa8-0-3 !INFO    | scylla:  [shard 0] gossip - Disable and wait for gossip loop started 


2020-05-25T01:46:24+00:00  rolling-upgrade-4-0-debian-stretch-db-node-5a671aa8-0-3 !INFO    | scylla:  [shard 0] init - Scylla version 3.3.2-0.20200510.c8c057f5f8 shutdown c
omplete.

2020-05-25T01:46:26+00:00  rolling-upgrade-4-0-debian-stretch-db-node-5a671aa8-0-3 !NOTICE  | sudo: scylla-test : TTY=unknown ; PWD=/home/scylla-test ; USER=root ; COMMAND=/
usr/bin/apt-get dist-upgrade scylla -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold --force-yes --allow-unauthenticated


```
#### Started scylla-server after upgrade

```
2020-05-25T01:47:41+00:00  rolling-upgrade-4-0-debian-stretch-db-node-5a671aa8-0-3 !NOTICE  | sudo: scylla-test : TTY=unknown ; PWD=/home/scylla-test ; USER=root ; COMMAND=/bin/systemctl start scylla-server.service

2020-05-25T01:47:41+00:00  rolling-upgrade-4-0-debian-stretch-db-node-5a671aa8-0-3 !INFO    | scylla:  [shard 0] init - installing SIGHUP handler
2020-05-25T01:47:41+00:00  rolling-upgrade-4-0-debian-stretch-db-node-5a671aa8-0-3 !INFO    | scylla:  [shard 0] init - Scylla version 4.0.1-0.20200524.8d9bc57aca6 with buil
d-id 778b5fddea1d144ace993fe09de0ef6f050bafe6 starting ...

< t:2020-05-25 01:48:02,716 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [scylla-test@10.142.0.85]: Command "sudo systemctl start scylla-server.service" finished with status 0

```

#### start to wait_db_up() after start cmd returned.

```
< t:2020-05-25 01:48:03,672 f:wait.py         l:50   c:sdcm.wait            p:DEBUG > wait_for: Retrying Node rolling-upgrade-4-0-debian-stretch-db-node-5a671aa8-0-3 [35.   185.31.226 | 10.142.0.85] (seed: False): Waiting for DB services to be up: attempt 1 ended with: False

< t:2020-05-25 01:49:03,757 f:wait.py         l:50   c:sdcm.wait            p:DEBUG > wait_for: Retrying Node rolling-upgrade-4-0-debian-stretch-db-node-5a671aa8-0-3 [35.185
.31.226 | 10.142.0.85] (seed: False): Waiting for DB services to be up: attempt 2 ended with: False

< t:2020-05-25 01:49:40,750 f:wait.py         l:64   c:sdcm.wait            p:ERROR > Wait for: Node rolling-upgrade-4-0-debian-stretch-db-node-5a671aa8-0-3 [35.185.31.226  | 10.142.0.85] (seed: False): Waiting for DB services to be up: timeout - 500 seconds - expired
```

Actually the wait_db_up() only wait for 97 seconds, not 500 seconds

@fruch @fgelcer  @bentsi

**Comment by fruch** [comment] 2020-05-27 11:07
this stopped waiting since a CRITICAL event was raised.
CRITICAL event stops everything, including the `wait_for()` functions.

two options here:
1) handle/figure the root cause reason for the c-s failure
2) use the PR @juliayakovlev worked on, to mark specific c-s threads as non critical

**Comment by juliayakovlev** [comment] 2020-05-27 11:16
> this stopped waiting since a CRITICAL event was raised.
> CRITICAL event stops everything, including the `wait_for()` functions.
> 
> two options here:
> 
> 1. handle/figure the root cause reason for the c-s failure
> 2. use the PR @juliayakovlev worked on, to mark specific c-s threads as non critical

It's #2172 . Merged and backported to 4.0 and 4.1

**Comment by amoskong** [comment] 2020-05-27 11:18
> this stopped waiting since a CRITICAL event was raised.
> CRITICAL event stops everything, including the `wait_for()` functions.

The background workload failed an interrupt the test, so the wait_for() was also interrupted as expected, so it's not a real sct issue.
 
> two options here:
> 
> 1. handle/figure the root cause reason for the c-s failure

The workload failed for 'com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-0-debian-stretch-db-node-5a671aa8-0-4.c.skilled-adapter-452.internal/10.142.0.89:9042) was overloaded: Too many in flight hints: 10485768'
- related issue: https://github.com/scylladb/scylla/issues/4935

> 2. use the PR @juliayakovlev worked on, to mark specific c-s threads as non critical

This PR is helpful.
- https://github.com/scylladb/scylla-cluster-tests/pull/2172/files

I saw the PR had been backported to sct branch-4.0, I had asked Bentsi to check.

**Comment by bentsi** [comment] 2020-06-02 09:48
closing since this is not an issue. The test stopped due to failed c-s.

**Closed** 2020-06-02 09:47 UTC

**Comment by amoskong** [comment] 2020-06-02 09:58
> closing since this is not an issue. The test stopped due to failed c-s.

Yes, thanks.
