### ISSUE TITLE
Add remove DC nemesis new node status is UJ 

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#4358] opened 2022-01-19 11:54 UTC
**Installation details**
Scylla version (or git commit hash): 4.7.dev with build-id 8bcd23fa0

Cluster size: 4 nodes (i3en.2xlarge)

Scylla running with shards number (live nodes):

longevity-twcs-48h-master-db-node-860131e4-1 (63.35.237.128 | 10.0.0.23)
longevity-twcs-48h-master-db-node-860131e4-2 (34.253.180.241 | 10.0.0.56)
longevity-twcs-48h-master-db-node-860131e4-4 (34.245.88.221 | 10.0.2.174)
longevity-twcs-48h-master-db-node-860131e4-5 (52.30.240.248 | 10.0.0.153)
longevity-twcs-48h-master-db-node-860131e4-7 (3.250.16.7 | 10.0.2.201)
OS / Image: ami-07027e06b9301e5cb (aws: eu-west-1)

Test: longevity-twcs-48h-test

Test id: 860131e4-2316-418f-bf92-2999a904f0fb

Test name: longevity_twcs_test/longevity-twcs-48h-test

Test config file(s):

longevity-twcs-48h.yaml

**Issue description**

Nemesis failed with: 

```
2022-01-14 18:08:26.284: (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=7dc0ad58-cbcf-4fba-9857-817b9032efaf: type=NodeStatus node=longevity-twcs-48h-master-db-node-860131e4-1 error=Current node 10.0.0.23. Node with 10.0.2.201 (not target node) status is UJ
```

**Logs**

Restore Monitor Stack command: $ hydra investigate show-monitor 860131e4-2316-418f-bf92-2999a904f0fb
Restore monitor on AWS instance using Jenkins job
Show all stored logs command: $ hydra investigate show-logs 860131e4-2316-418f-bf92-2999a904f0fb
Logs:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/860131e4-2316-418f-bf92-2999a904f0fb/20220114_182043/db-cluster-860131e4.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/860131e4-2316-418f-bf92-2999a904f0fb/20220114_182043/monitor-set-860131e4.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/860131e4-2316-418f-bf92-2999a904f0fb/20220114_182043/loader-set-860131e4.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/860131e4-2316-418f-bf92-2999a904f0fb/20220114_182043/sct-runner-860131e4.tar.gz
Jenkins job URL

**Comment by soyacz** [comment] 2022-01-19 13:48
Possible cause: only system tables replication strategy was changed to Network, causing streaming of all user keyspaces to new node. Due high volume, node didn't show up as UN for more than 900s (timeout).
I'll test this hyphotesis and provide a fix.

**Comment by fgelcer** [comment] 2022-02-15 08:35
@soyacz , could you please confirm if the issue is fixed (and if it is fixed, close this issue)?

**Comment by soyacz** [comment] 2022-02-15 10:31
Yes, I confirm. Fixed in https://github.com/scylladb/scylla-cluster-tests/pull/4314

**Closed by soyacz** 2022-02-15 10:31 UTC
