### ISSUE TITLE
After multiple hard reboots a node eventually loses connection to all other nodes in the cluster

### ISSUE THREAD

**Issue by dimakr** [scylladb/scylla-cluster-tests#8553] opened 2024-08-15 07:49 UTC
## Packages

Scylla version: `6.2.0~dev-20240809.3745d0a53457` with build-id `d168ac61c2ac38ef15c6deba485431e666a8fdef`
Kernel Version: `6.8.0-1013-aws`

## Issue description
`disrupt_method multiple_hard_reboot_node` nemesis performed 10 hard reboots of a node-5 in a row (the number of reboots is randomly selected from range 2 to 10 for each test run) - the 1st one started ad `08:41:02`, the 10th finished at `08:54:07`. All reboots finished successfully, scylla started after 10th reboot at `08:54:07`:
```
08:54:07.223699 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:main] init - Scylla version 6.2.0~dev-0.20240809.3745d0a53457 initialization completed. 
```
Then post-nemesis check health of the cluster was performed and passed, and the nemesis was marked as successfully finished at `09:18:14`.

Next `replace_service_level_using_detach_during_load` nemesis was scheduled at `09:23:14`. At the beginning of each nemesis cluster health check is performed. This nemesis passed the pre-nemesis health check, but the nemesis disruption itself was not executed as it is dedicated for SLA tests only. At `09:47:15` the nemesis was marked as skipped.

Next `network_reject_node_exporter` nemesis was scheduled at `09:47:15` and its pre-nemesis cluster health check failed - `nodetool status` check on node-5 (the one that was hard rebooted multiple times previously) returned at `09:54:26` that it sees all other nodes as down:
```
< t:2024-08-10 09:54:26,720 f:cluster.py      l:2701 c:sdcm.cluster         p:DEBUG > Check the health of the node `longevity-tls-50gb-3d-master-db-node-7b8958f1-5' [attempt scylladb/scylladb#1]                           │
< t:2024-08-10 09:54:26,896 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: Datacenter: eu-west                                                                                    │
< t:2024-08-10 09:54:26,897 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: ===================                                                                                    │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: Status=Up/Down                                                                                         │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: |/ State=Normal/Leaving/Joining/Moving                                                                 │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: -- Address     Load     Tokens Owns Host ID                              Rack                          │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: DN 10.4.21.103 19.41 GB 256    ?    af2bd628-7745-4085-baa8-6199972679e8 1c                            │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: UN 10.4.21.183 19.54 GB 256    ?    b4273168-eea5-459e-8567-ee7350612c57 1c                            │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: DN 10.4.21.250 20.67 GB 256    ?    ce1395db-9b0e-47b8-9853-8806c70459f4 1c                            │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: DN 10.4.22.115 19.49 GB 256    ?    15b3be5f-54bc-473a-b823-2ea2945a6bf2 1c                            │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: DN 10.4.23.56  19.74 GB 256    ?    c26fe030-4ef8-4d18-84f1-a13d65fbcf01 1c                            │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: DN 10.4.23.78  24.07 GB 256    ?    8f147dbe-f7d4-409a-be66-32937d802a8c 1c   
```

At `09:54:24` In system.log on node-5 there are records that the other nodes are marked down in gossip:
```
Aug 10 09:54:22.939111 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  3:strm] gossip - failure_detector_loop: Send echo to node 10.4.22.115, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Aug 10 09:54:22.939121 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  3:strm] gossip - failure_detector_loop: Mark node 10.4.22.115 as DOWN
Aug 10 09:54:22.940995 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - InetAddress 15b3be5f-54bc-473a-b823-2ea2945a6bf2/10.4.22.115 is now DOWN, status = NORMAL
Aug 10 09:54:23.147016 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - failure_detector_loop: Send echo to node 10.4.23.78, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Aug 10 09:54:23.147026 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - failure_detector_loop: Mark node 10.4.23.78 as DOWN
Aug 10 09:54:23.148989 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - InetAddress 8f147dbe-f7d4-409a-be66-32937d802a8c/10.4.23.78 is now DOWN, status = NORMAL
Aug 10 09:54:23.535627 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  1:strm] gossip - failure_detector_loop: Send echo to node 10.4.21.250, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Aug 10 09:54:23.535637 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  1:strm] gossip - failure_detector_loop: Mark node 10.4.21.250 as DOWN
Aug 10 09:54:23.536990 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - InetAddress ce1395db-9b0e-47b8-9853-8806c70459f4/10.4.21.250 is now DOWN, status = NORMAL
Aug 10 09:54:23.757903 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  2:strm] gossip - failure_detector_loop: Send echo to node 10.4.21.103, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Aug 10 09:54:23.757913 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  2:strm] gossip - failure_detector_loop: Mark node 10.4.21.103 as DOWN
Aug 10 09:54:23.759997 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - InetAddress af2bd628-7745-4085-baa8-6199972679e8/10.4.21.103 is now DOWN, status = NORMAL
Aug 10 09:54:23.890642 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  4:strm] gossip - failure_detector_loop: Send echo to node 10.4.23.56, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Aug 10 09:54:23.890653 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  4:strm] gossip - failure_detector_loop: Mark node 10.4.23.56 as DOWN
Aug 10 09:54:23.892488 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - InetAddress c26fe030-4ef8-4d18-84f1-a13d65fbcf01/10.4.23.56 is now DOWN, status = NORMAL
``` 

To summarize, after multiple reboots of node-5 there were no other disruptions executed during the test and the cluster was able to pass a few cluster health checks, but eventually within an hour the node-5 lost connection to other nodes.

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

Node lost connection to other cluster nodes, over time, after multiple hard reboots

## How frequently does it reproduce?

No occurrences of the issue were noticed previously.

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-7b8958f1-7 (54.217.202.232 | 10.4.21.250) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-6 (52.212.55.136 | 10.4.23.56) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-5 (54.73.59.86 | 10.4.21.183) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-4 (52.48.211.247 | 10.4.22.17) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-3 (46.137.188.213 | 10.4.22.115) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-2 (34.246.25.227 | 10.4.23.78) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-1 (63.35.206.244 | 10.4.21.103) (shards: 14)

OS / Image: `ami-05a75d3ca4e6ebd9f` (aws: undefined_region)

Test: `longevity-50gb-3days-test`
Test id: `7b8958f1-4a7f-4cef-a68d-32c1393493b0`
Test name: `scylla-master/tier1/longevity-50gb-3days-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/05b966987503dfe0602025e101fff695d0bf169c/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7b8958f1-4a7f-4cef-a68d-32c1393493b0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7b8958f1-4a7f-4cef-a68d-32c1393493b0)
- Show all stored logs command: `$ hydra investigate show-logs 7b8958f1-4a7f-4cef-a68d-32c1393493b0`

## Logs:
- **db-cluster-7b8958f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/db-cluster-7b8958f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/db-cluster-7b8958f1.tar.gz)
- **sct-runner-events-7b8958f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/sct-runner-events-7b8958f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/sct-runner-events-7b8958f1.tar.gz)
- **sct-7b8958f1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/sct-7b8958f1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/sct-7b8958f1.log.tar.gz)
- **loader-set-7b8958f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/loader-set-7b8958f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/loader-set-7b8958f1.tar.gz)
- **monitor-set-7b8958f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/monitor-set-7b8958f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/monitor-set-7b8958f1.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-50gb-3days-test/32/)
[Argus](https://argus.scylladb.com/test/98050732-dfe3-464c-a66a-f235bad30829/runs?additionalRuns[]=7b8958f1-4a7f-4cef-a68d-32c1393493b0)
</details>

**Comment by fruch** [comment] 2024-09-04 19:36
Me and @roy found the reason for external communication, SG was open for ssh, we close it as it should have been.

As for the network issue we are facing here, 

@juliayakovlev let's try to reproduce with nemesis that hard restart node.

My gut feeling is that we might have issues with the network setup after reboot of new, we need a quicker reproducer.

**Comment by fruch** [comment] 2024-09-15 06:00
@juliayakovlev 

please look at this one, seems like we are having an issue with multiple network not working after node is rebooted.

**Comment by juliayakovlev** [comment] 2024-09-16 15:46
This test started to use multi network configuration at 3.6.2024. But this issue happened first time at 24.7.2024 (https://argus.scylladb.com/test/98050732-dfe3-464c-a66a-f235bad30829/runs?additionalRuns[]=856e2796-0eb3-4051-a5d0-305442ceb57a) . 
But in [this run](https://argus.scylladb.com/test/98050732-dfe3-464c-a66a-f235bad30829/runs?additionalRuns[]=a7693394-aaef-466b-9516-f2d3d592d6e7) from 13.7.2024 this issue did not happened.

Trying to reproduce the issue with MultipleHardRebootNodeMonkey.

**Comment by juliayakovlev** [comment] 2024-09-16 17:10
```
< t:2024-08-03 10:37:12,301 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.224>: Aug 03 10:37:12 longevity-tls-50gb-3d-master-monitor-node-6f2ed542-1 scylla-manager[9562]: {"L":"ERROR","T":"
2024-08-03T10:37:12.006Z","N":"healthcheck.CQL healthcheck","M":"Parallel hosts check failed","host":"10.4.21.245","error":"setup: dial tcp :0->10.4.21.245:9142: connect: connection refused","_trace_id":"zMxUxZM
CRzWFShZ0hPjmkw","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.c
om/scylladb/scylla-manager/v3/pkg/service/healthcheck.runner.checkHosts.func2\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/healthcheck/runner.go:101\ngithub.com/scylladb/scylla-manager/v3/pkg/util/parall
el.Run.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/util/parallel/parallel.go:79"}
< t:2024-08-03 10:37:12,312 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.224>: Aug 03 10:37:12 longevity-tls-50gb-3d-master-monitor-node-6f2ed542-1 scylla-manager[9562]: {"L":"ERROR","T":"
2024-08-03T10:37:12.006Z","N":"healthcheck.CQL healthcheck","M":"Parallel hosts check failed","host":"10.4.21.188","error":"setup: dial tcp :0->10.4.21.188:9142: connect: connection refused","_trace_id":"zMxUxZM
CRzWFShZ0hPjmkw","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.c
om/scylladb/scylla-manager/v3/pkg/service/healthcheck.runner.checkHosts.func2\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/healthcheck/runner.go:101\ngithub.com/scylladb/scylla-manager/v3/pkg/util/parall
el.Run.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/util/parallel/parallel.go:79"}
< t:2024-08-03 10:37:12,312 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.224>: Aug 03 10:37:12 longevity-tls-50gb-3d-master-monitor-node-6f2ed542-1 scylla-manager[9562]: {"L":"ERROR","T":"
2024-08-03T10:37:12.006Z","N":"healthcheck.CQL healthcheck","M":"Parallel hosts check failed","host":"10.4.21.218","error":"setup: dial tcp :0->10.4.21.218:9142: connect: connection refused","_trace_id":"zMxUxZM
CRzWFShZ0hPjmkw","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.c
om/scylladb/scylla-manager/v3/pkg/service/healthcheck.runner.checkHosts.func2\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/healthcheck/runner.go:101\ngithub.com/scylladb/scylla-manager/v3/pkg/util/parall
el.Run.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/util/parallel/parallel.go:79"}
< t:2024-08-03 10:37:12,312 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.224>: Aug 03 10:37:12 longevity-tls-50gb-3d-master-monitor-node-6f2ed542-1 scylla-manager[9562]: {"L":"ERROR","T":"
2024-08-03T10:37:12.006Z","N":"healthcheck.CQL healthcheck","M":"Parallel hosts check failed","host":"10.4.22.148","error":"setup: dial tcp :0->10.4.22.148:9142: connect: connection refused","_trace_id":"zMxUxZM
CRzWFShZ0hPjmkw","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.c
om/scylladb/scylla-manager/v3/pkg/service/healthcheck.runner.checkHosts.func2\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/healthcheck/runner.go:101\ngithub.com/scylladb/scylla-manager/v3/pkg/util/parall
el.Run.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/util/parallel/parallel.go:79"}
< t:2024-08-03 10:37:12,312 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.224>: Aug 03 10:37:12 longevity-tls-50gb-3d-master-monitor-node-6f2ed542-1 scylla-manager[9562]: {"L":"ERROR","T":"
2024-08-03T10:37:12.006Z","N":"healthcheck.CQL healthcheck","M":"Parallel hosts check failed","host":"10.4.22.222","error":"setup: dial tcp :0->10.4.22.222:9142: connect: connection refused","_trace_id":"zMxUxZM
CRzWFShZ0hPjmkw","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.c
om/scylladb/scylla-manager/v3/pkg/service/healthcheck.runner.checkHosts.func2\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/healthcheck/runner.go:101\ngithub.com/scylladb/scylla-manager/v3/pkg/util/parall
el.Run.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/util/parallel/parallel.go:79"}

```

```
< t:2024-08-03 10:37:12,703 f:cluster_aws.py  l:497  c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-50gb-3d-master-db-node-6f2ed542-7 [79.125.27.189 | 10.4.22.222]: Sorted interfaces: [NetworkInterface(ipv4
_public_address='79.125.27.189', ipv6_public_addresses=['2a05:d018:12e3:f002:46da:2b5d:eb8f:d34b'], ipv4_private_addresses=['10.4.9.156'], ipv6_private_address='', dns_private_name='ip-10-4-9-156.eu-west-1.compu
te.internal', dns_public_name='ec2-79-125-27-189.eu-west-1.compute.amazonaws.com', device_index=0), NetworkInterface(ipv4_public_address=None, ipv6_public_addresses=['2a05:d018:12e3:f005:7b0a:1e0d:e8d1:0329'], i
pv4_private_addresses=['10.4.22.222'], ipv6_private_address='', dns_private_name='ip-10-4-22-222.eu-west-1.compute.internal', dns_public_name=None, device_index=1)]
```

```
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG > /10.4.22.222
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   generation:1722656360
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   heartbeat:76957
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   LOAD:17492227739
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   STATUS:NORMAL,9222693218404302345
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   CDC_STREAMS_TIMESTAMP:v2;1722656428071;f8bd2926-5149-11ef-44a5-d34f93b96fc5
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   IGNOR_MSB_BITS:12
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   SHARD_COUNT:14
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   DC:eu-west
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   SCHEMA_TABLES_VERSION:3
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   RACK:1c
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   RPC_READY:1
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   NET_VERSION:0
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   HOST_ID:ce53f8cb-2f70-4cbe-b3db-3537b33336ae
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   RPC_ADDRESS:10.4.22.222
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   RELEASE_VERSION:3.0.8
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   VIEW_BACKLOG:19593:877238681:1722681431300
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   SUPPORTED_FEATURES:AGGREGATE_STORAGE_OPTIONS,ALTERNATOR_TTL,CDC,CDC_GENERATIONS_V2,COLLECTION_INDEXING,COMPUTED_COLUMNS,COR
RECT_COUNTER_ORDER,CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_FOR_NULL_VALUES,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,
EMPTY_REPLICA_MUTATION_PAGES,EMPTY_REPLICA_PAGES,GROUP0_SCHEMA_VERSIONING,HINTED_HANDOFF_SEPARATE_CONNECTION,HOST_ID_BASED_HINTED_HANDOFF,INDEXES,LARGE_COLLECTION_DETECTION,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT
,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,MD_SSTABLE_FORMAT,ME_SSTABLE_FORMAT,NONFROZEN_UDTS,PARALLELIZED_AGGREGATION,PER_TABLE_CACHING,PER_TABLE_PARTITIONERS,RANGE_SCAN_DATA_VARIANT,RANGE_TOMBSTONES,RANGE_TOMBSTONE
_AND_DEAD_ROWS_DETECTION,ROLES,ROW_LEVEL_REPAIR,SCHEMA_COMMITLOG,SCHEMA_TABLES_V3,SECONDARY_INDEXES_ON_STATIC_COLUMNS,SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT,STREAM_WITH_RPC_STREAM,SUPPORTS_CONSISTENT_TOPOLOGY_CHANG
ES,SUPPORTS_RAFT_CLUSTER_MANAGEMENT,TABLETS,TABLE_DIGEST_INSENSITIVE_TO_EXPIRY,TOMBSTONE_GC_OPTIONS,TOPOLOGY_REQUESTS_TYPE_COLUMN,TRUNCATION_TABLE,TYPED_ERRORS_IN_READ_RPC,UDA,UDA_NATIVE_PARALLELIZED_AGGREGATION
,UNBOUNDED_RANGE_TOMBSTONES,UUID_SSTABLE_IDENTIFIERS,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   CACHE_HITRATES:system_distributed.cdc_streams_descriptions_v2:0.000000;system_distributed.service_levels:0.000000;system_di
stributed.view_build_status:0.000000;system_distributed_everywhere.cdc_generation_descriptions_v2:0.000000;mview.users:0.999263;mview.users_by_first_name:0.986998;system_traces.node_slow_log_time_idx:0.000000;sy
stem_traces.sessions_time_idx:0.000000;system_traces.node_slow_log:0.000000;system_traces.events:0.000000;system_distributed.cdc_generation_timestamps:0.000000;mview.users_by_last_name:0.986726;system_traces.ses
sions:0.000000;keyspace1.standard1:0.509396;
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   SCHEMA:6499f9b8-5167-11ef-7e77-f672457e09dd
< t:2024-08-03 10:37:12,125 f:cluster.py      l:2772 c:sdcm.cluster         p:DEBUG >   SNITCH_NAME:org.apache.cassandra.locator.Ec2Snitch
```

```
< t:2024-08-03 10:37:13,735 f:cluster.py      l:2698 c:sdcm.cluster         p:DEBUG > One or more node `longevity-tls-50gb-3d-master-db-node-6f2ed542-7' health validation has failed
```

**Comment by fruch** [comment] 2024-09-16 20:40
@juliayakovlev what is this log, in the last comment? The context of it isn't clear

**Comment by juliayakovlev** [comment] 2024-09-17 06:15
> [@juliayakovlev](https://github.com/juliayakovlev) what is this log, in the last comment? The context of it isn't clear

I am collecting the info meanwhile

**Comment by juliayakovlev** [comment] 2024-09-23 09:00
Reproduced https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=fb21a056-02c8-4c86-888e-f3fb5303c1ff

Branch: `issue_sct_8553`
The issue is reproduced with 2 nemeses: [`disrupt_no_corrupt_repair`, `disrupt_multiple_hard_reboot_node`] after `disrupt_no_corrupt_repair`

**Comment by juliayakovlev** [comment] 2024-09-23 15:15
> Reproduced [https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=fb21a056-02c8-4c86-888e-f3fb5303c1ff](https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns%5B%5D=fb21a056-02c8-4c86-888e-f3fb5303c1ff)
> 
> Branch: `issue_sct_8553` The issue is reproduced with 2 nemeses: [`disrupt_no_corrupt_repair`, `disrupt_multiple_hard_reboot_node`] after `disrupt_no_corrupt_repair`

Actually not. It is the problem of https://github.com/scylladb/scylladb/issues/18059

**Comment by juliayakovlev** [comment] 2024-09-23 16:07
I ran the tests with `disrupt_multiple_hard_reboot_node` only - the problem was not reproduced

**Comment by fruch** [comment] 2024-09-23 20:06
> I ran the tests with `disrupt_multiple_hard_reboot_node` only - the problem was not reproduced

Can you try running it with the scylla version from reported failures ?

If that doesn't reproduce, we'll leave it for now

**Comment by juliayakovlev** [comment] 2024-09-24 05:43
> > I ran the tests with `disrupt_multiple_hard_reboot_node` only - the problem was not reproduced
> 
> Can you try running it with the scylla version from reported failures ?
> 
> If that doesn't reproduce, we'll leave it for now

I ran it with ami from issue

**Comment by juliayakovlev** [comment] 2024-09-26 08:03
https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=23a99995-959d-4c8a-9067-f49c326f5a15
The test was run about 23 hours with `disrupt_multiple_hard_reboot_node` only. The issue was not reproduced

**Comment by juliayakovlev** [comment] 2024-09-26 09:56
https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=641f6728-624b-418d-9205-b8d4beac763c

2 network interfaces
Test failed after about 55 mins, `disrupt_multiple_hard_reboot_node` nemesis only.
With ami-0071c4f2153cf06c2 (from issue)

**Comment by juliayakovlev** [comment] 2024-09-29 16:27
Created branch `issue_sct_8553`. The change there -  do not run `sdcm.provision.aws.utils.configure_eth1_script`, not re-configure secondary network interface.

Run 2 tests:
1. Test with `disrupt_multiple_hard_reboot_node` only - PASSED. The test were run 2 days
2. Regular test with all nemeses (according to test yaml) - _running_
https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=21961db0-285c-4b84-a4da-4d70be149e06

**Comment by fruch** [comment] 2024-09-29 16:48
> Created branch `issue_sct_8553`. The change there -  do not run `sdcm.provision.aws.utils.configure_eth1_script`, not re-configure secondary network interface.
> 
> Run 2 tests:
> 1. Test with `disrupt_multiple_hard_reboot_node` only - PASSED. The test were run 2 days
> 2. Regular test with all nemeses (according to test yaml) - _running_
> https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=21961db0-285c-4b84-a4da-4d70be149e06

Let's open a PR, and discuss testing needed there

**Comment by juliayakovlev** [comment] 2024-09-30 07:40
> > Created branch `issue_sct_8553`. The change there -  do not run `sdcm.provision.aws.utils.configure_eth1_script`, not re-configure secondary network interface.
> > Run 2 tests:
> > 
> > 1. Test with `disrupt_multiple_hard_reboot_node` only - PASSED. The test were run 2 days
> > 2. Regular test with all nemeses (according to test yaml) - _running_
> >    [https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=21961db0-285c-4b84-a4da-4d70be149e06](https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns%5B%5D=21961db0-285c-4b84-a4da-4d70be149e06)
> 
> Let's open a PR, and discuss testing needed there

@fruch https://github.com/scylladb/scylla-cluster-tests/pull/8883

**Comment by juliayakovlev** [comment] 2024-10-13 08:15
Running the final test

**Closed** 2024-10-13 13:47 UTC
