### ISSUE TITLE
Bench stress fails on start: `cannot validate certificate`...`because it doesn't contain any IP SANs`

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#5291] opened 2022-09-19 09:37 UTC
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: 8abedff1-8198-43d2-bd48-04a2c0f95f87
* job: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-test/483/

### Description

At `2022-09-14 18:45:11,290`, as part of a ks_truncate_large_partition nemesis, a scylla bench started as follows:
`scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=10 -clustering-row-count=5555 -clustering-row-size=uniform:10..20 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=60s -keyspace ks_truncate_large_partition -table test_table -tls  -error-at-row-limit 1000`
(Since the run has two loaders, the stress ran twice - one at each)

The stress, however, instantly failed with the following:
`2022/09/14 18:45:12 gocql: unable to create session: unable to discover protocol version: x509: cannot validate certificate for 10.12.3.66 because it doesn't contain any IP SANs`
`2022/09/14 18:45:22 gocql: unable to create session: unable to discover protocol version: x509: cannot validate certificate for 10.12.0.218 because it doesn't contain any IP SANs`

When I examined the nodes' logs, I saw the following message in every living node:
```
2022-09-14T18:45:12+00:00 longevity-100gb-4h-master-db-node-8abedff1-2     !INFO | scylla[7862]:  [shard  1] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
2022-09-14T18:45:23+00:00 longevity-100gb-4h-master-db-node-8abedff1-2     !INFO | scylla[7862]:  [shard  1] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
```
```
2022-09-14T18:45:12+00:00 longevity-100gb-4h-master-db-node-8abedff1-3     !INFO | scylla[7968]:  [shard  0] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
2022-09-14T18:45:23+00:00 longevity-100gb-4h-master-db-node-8abedff1-3     !INFO | scylla[7968]:  [shard  0] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
```
```
2022-09-14T18:45:12+00:00 longevity-100gb-4h-master-db-node-8abedff1-4     !INFO | scylla[7993]:  [shard  2] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
2022-09-14T18:45:23+00:00 longevity-100gb-4h-master-db-node-8abedff1-4     !INFO | scylla[7993]:  [shard  2] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
```
```
2022-09-14T18:45:12+00:00 longevity-100gb-4h-master-db-node-8abedff1-7     !INFO | scylla[7787]:  [shard  1] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
2022-09-14T18:45:23+00:00 longevity-100gb-4h-master-db-node-8abedff1-7     !INFO | scylla[7787]:  [shard  1] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
```
```
2022-09-14T18:45:12+00:00 longevity-100gb-4h-master-db-node-8abedff1-8     !INFO | scylla[894]:  [shard  0] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
2022-09-14T18:45:23+00:00 longevity-100gb-4h-master-db-node-8abedff1-8     !INFO | scylla[894]:  [shard  0] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
```
```
2022-09-14T18:45:12+00:00 longevity-100gb-4h-master-db-node-8abedff1-9     !INFO | scylla[13965]:  [shard  0] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
2022-09-14T18:45:23+00:00 longevity-100gb-4h-master-db-node-8abedff1-9     !INFO | scylla[13965]:  [shard  0] cql_server - exception while processing connection: std::system_error (error GnuTLS:-12, A TLS fatal alert has been received.)
```

**Expected behavior:** bench stress will succeed

**Actual behavior:** the bench stress is DOA

## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `5.2.0~dev-20220914.6799e766ca95` with build-id `3f6897811f76b9db7f4143fc4cd299a3d7121b02`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-master-db-node-8abedff1-9 (3.239.247.226 | 10.12.3.66) (shards: 14)
- longevity-100gb-4h-master-db-node-8abedff1-8 (18.215.63.48 | 10.12.0.218) (shards: 14)
- longevity-100gb-4h-master-db-node-8abedff1-7 (54.91.37.160 | 10.12.3.240) (shards: 14)
- longevity-100gb-4h-master-db-node-8abedff1-6 (18.213.110.13 | 10.12.0.197) (shards: 14)
- longevity-100gb-4h-master-db-node-8abedff1-5 (44.197.243.201 | 10.12.1.21) (shards: 14)
- longevity-100gb-4h-master-db-node-8abedff1-4 (3.93.35.128 | 10.12.0.168) (shards: 14)
- longevity-100gb-4h-master-db-node-8abedff1-3 (3.235.9.6 | 10.12.2.138) (shards: 14)
- longevity-100gb-4h-master-db-node-8abedff1-2 (44.201.16.18 | 10.12.0.102) (shards: 14)
- longevity-100gb-4h-master-db-node-8abedff1-1 (3.237.170.51 | 10.12.1.79) (shards: 14)

OS / Image: `ami-06fbb6ed9ea9f3870` (aws: us-east-1)

Test: `longevity-100gb-4h-test`
Test name: `scylla-master/longevity/longevity-100gb-4h-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/7ae3b8cf46fd9240fe411a3ce1d5d41dc848256a/test-cases/longevity/longevity-100gb-4h.yaml)

## Logs:
- **db-cluster-8abedff1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8abedff1-8198-43d2-bd48-04a2c0f95f87/20220914_191655/db-cluster-8abedff1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8abedff1-8198-43d2-bd48-04a2c0f95f87/20220914_191655/db-cluster-8abedff1.tar.gz)
- **monitor-set-8abedff1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8abedff1-8198-43d2-bd48-04a2c0f95f87/20220914_191655/monitor-set-8abedff1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8abedff1-8198-43d2-bd48-04a2c0f95f87/20220914_191655/monitor-set-8abedff1.tar.gz)
- **loader-set-8abedff1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8abedff1-8198-43d2-bd48-04a2c0f95f87/20220914_191655/loader-set-8abedff1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8abedff1-8198-43d2-bd48-04a2c0f95f87/20220914_191655/loader-set-8abedff1.tar.gz)
- **sct-runner-8abedff1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8abedff1-8198-43d2-bd48-04a2c0f95f87/20220914_191655/sct-runner-8abedff1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8abedff1-8198-43d2-bd48-04a2c0f95f87/20220914_191655/sct-runner-8abedff1.tar.gz)
- **parallel-timelines-report-8abedff1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8abedff1-8198-43d2-bd48-04a2c0f95f87/20220914_191655/parallel-timelines-report-8abedff1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8abedff1-8198-43d2-bd48-04a2c0f95f87/20220914_191655/parallel-timelines-report-8abedff1.tar.gz)

**Comment by vponomaryov** [comment] 2022-09-19 09:58
I guess it is duplicate of this one -> [The same](https://github.com/scylladb/scylla-cluster-tests/issues/2850)

**Comment by vponomaryov** [comment] 2022-09-19 10:09
@fruch The last message there is the same thing from my point of view -> @ilya-rarov 's comment here: https://github.com/scylladb/scylla-cluster-tests/issues/2850#issuecomment-1248303770

**Comment by ilya-rarov** [comment] 2022-09-19 10:21
@vponomaryov yes, you are correct. I described the same problem in that comment. I thought https://github.com/scylladb/scylla-cluster-tests/issues/2850 was the appropriate one, so I didn't open a new issue for that. But I wasn't 100% sure :frowning_face:

**Closed** 2024-09-22 00:57 UTC
Labels: no-issue-activity
