### ISSUE TITLE
High avocado cpu consumption

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-cluster-tests#129] opened 2016-07-17 06:55 UTC
```
 2527 colord    20   0 2858252 108236   9868 S 173.4  0.3 169:17.94 0 avocado
```

**Comment by lmr** [comment] 2016-07-19 07:40
@avikivity avocado runs test processes as subprocesses, then keeps polling the state of each test process. I remember we made some improvements on this front, although I believe there's room for more improvement. I'm not sure how quickly I can jump into this, though.

**Comment by avikivity** [comment] 2016-07-19 07:58
I'm sure there's no need to poll continuously.

**Comment by ldoktor** [comment] 2016-08-02 10:33
Hello guys, I have no experience with the scylla-cluster-tests, but avocado itself mainly sleeps. It'd help if you could include the `pstree` of the main avocado process (or simply cut the rest), because this `avocado` process is most probably  the actual test's process. There are several processes in avocado execution. The main ones are `main` and `test`:

```
main: avocado starts
main: fork and create test (which is still called avocado)
test: instantiate the test and report early_status
test: start the test (the process name is still `avocado` in ps)
main: read the early status
main: poll 1s for status update
main: check if process still exists/is running/...
test: test finishes
test: reports the final status
main: receives the status, checks the process finished, ...
main: proceeds with the next tests (goto line 2)
main: finishes
```

**Comment by ldoktor** [comment] 2016-08-02 10:56
OK, I looked at the code and the fault probably is on avocado side, not in test handling, but the process library... The `scylla-cluster-tests` runs stress command using `avocado.utils.process` and probably uses timeout. The problem is that when using timeout, the process library polls without any timeout, consuming high cpu, which is definitely not necessary. Let me take care of that...

**Comment by ldoktor** [comment] 2016-08-02 10:58
PS: Simple reproducer is:

```python
from avocado.utils import process
a=process.run("sleep 30", timeout=31)
```

**Comment by clebergnu** [comment] 2016-08-03 21:10
@lmr https://github.com/avocado-framework/avocado/pull/1350 has been merged.  Please check if it solves the specific issue you're experiencing.  Thanks!

**Comment by lmr** [comment] 2016-08-04 00:45
@clebergnu and @ldoktor, thanks guys. I was taking a look and indeed the parent process is not the responsible for high CPU consumption.

I'm currently looking at the remote library, which is handling all SSH connections established to the cluster nodes. Maybe the process changes here might help, although I have been using avocado 36.X to run the tests on, to keep a stable runtime on CI, and haven't yet tried the tests on newer versions.

**Comment by clebergnu** [comment] 2016-08-04 01:02
@lmr it should be easy to backport those into the 36lts branch and run a test just to make sure there were improvements.  If that turns out to be the case, we may evaluate adding those fixes to an upcoming 36.2 release.

**Comment by lmr** [comment] 2016-08-04 01:10
@clebergnu Yep, I'm testing a backported version of the fixes. I'll let you know soon.

**Comment by lmr** [comment] 2016-08-04 01:30
@clebergnu Indeed, the `avocado.utils.process` patches solve the high CPU consumption problem. If you guys can backport https://github.com/avocado-framework/avocado/pull/1350 to the 36.X branch that'd be great!

**Comment by lmr** [comment] 2016-08-04 01:36
So @avikivity, we have a fix. I'm leaving this open until we have a new 36.X avocado release, and the fixes are deployed to jenkins.

**Comment by clebergnu** [comment] 2016-08-04 01:49
@lmr in the best interest of the LTS principles, I posted a PR with the fix and nothing else:

https://github.com/avocado-framework/avocado/pull/1354

It works for me, but I'd be great if you could try that one also.  Once merged, I can make a release and new packages right away.

**Comment by lmr** [comment] 2016-08-08 14:38
Avocado 36.2 was deployed to our test nodes. Closing this issue.

**Closed by lmr** 2016-08-08 14:38 UTC
