### ISSUE TITLE
Test failed after "Connection reset by peer"

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#2081] opened 2020-04-26 08:58 UTC
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: lwt_500gb_longevity
* **scylla**: 4.0.rc2-0.20200421.89e79023aeb (ami-03aedf777a1b32ab7 - us-east-1)

### Logs
* job log: [sct.log.tar.gz](https://github.com/scylladb/scylla-cluster-tests/files/4534929/sct.log.tar.gz)

 
LWT 500g test was stopped because of ```Connection reset by peer``` when running command ```grep ^client_encryption_options: /etc/scylla/scylla.yaml -A 3 | grep enabled | awk '{print $2}'```. 
It's node property "is_client_encrypt"

This is output from log:
```
< t:2020-04-25 01:44:42,770 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@52.5.108.199]: Running command "grep ^client_encryption_options: /etc/scylla/scylla.yaml -A 3 | grep enabled | awk '{print $2}'
"...
< t:2020-04-25 01:44:42,950 f:remote.py       l:323  c:sdcm.remote          p:ERROR > [Errno 104] Connection reset by peer
< t:2020-04-25 01:44:42,963 f:tester.py       l:1556 c:sdcm.tester          p:INFO  > TearDown is starting...
< t:2020-04-25 01:44:42,963 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  > 2020-04-25 01:44:42.951: (InfoEvent Severity.NORMAL): message=TEST_END
...........................................
...........................................
...........................................

< t:2020-04-25 01:44:43,094 f:tester.py       l:1474 c:sdcm.tester          p:DEBUG > Stopping all resources
< t:2020-04-25 01:44:43,095 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@3.83.190.104]: Running command "pgrep -f cassandra-stress | xargs -I{}  kill -TERM -{}"...
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  > 2020-04-25 01:44:43.082: ======================================================================
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  > longevity_lwt_test.LWTLongevityTest.test_lwt_longevity
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  > ----------------------------------------------------------------------
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  > ERROR:
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  > test_lwt_longevity (longevity_lwt_test.LWTLongevityTest):
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  > Traceback (most recent call last):
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/sct/longevity_lwt_test.py", line 283, in test_lwt_longevity
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     self.test_custom_time()
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/sct/longevity_test.py", line 215, in test_custom_time
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     self._run_all_stress_cmds(stress_queue, params)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/sct/longevity_test.py", line 53, in _run_all_stress_cmds
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     stress_queue.append(self.run_stress_thread(**params))
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 727, in run_stress_thread
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     client_encrypt=self.db_cluster.nodes[0].is_client_encrypt,
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster.py", line 502, in is_client_encrypt
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     "grep ^client_encryption_options: /etc/scylla/scylla.yaml -A 3 | grep enabled | awk '{print $2}'", ignore_status=True)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/utils/decorators.py", line 121, in inner
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     return func(*args, **kwargs)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/remote.py", line 333, in run
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     result = _run()
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/utils/decorators.py", line 116, in inner
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     return func(*args, **kwargs)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/remote.py", line 318, in _run
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     result = self.connection.run(**command_kwargs)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "<decorator-gen-3>", line 2, in run
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 30, in opens
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     return method(self, *args, **kwargs)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 721, in run
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     return self._run(self._remote_runner(), command, **kwargs)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 101, in _run
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     return runner.run(command, **kwargs)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 291, in run
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     return self._run_body(command, **kwargs)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 315, in _run_body
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     self.start(command, shell, env)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/fabric/runners.py", line 36, in start
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     self.channel = self.context.create_session()
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "<decorator-gen-2>", line 2, in create_session
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 30, in opens
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     return method(self, *args, **kwargs)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 698, in create_session
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     channel = self.transport.open_session()
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 879, in open_session
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     timeout=timeout,
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1006, in open_channel
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     raise e
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2055, in run
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     ptype, m = self.packetizer.read_message()
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 459, in read_message
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     header = self.read_all(self.__block_size_in, check_rekey=True)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 301, in read_all
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >     x = self.__socket.recv(n)
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  > ConnectionResetError: [Errno 104] Connection reset by peer
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  >
< t:2020-04-25 01:44:43,094 f:sct_events.py   l:793  c:sdcm.sct_events      p:INFO  > ----------------------------------------------------------------------
```
I don't see other errors that can cause to the TearDown.

**The test flow:**
1. run c-s prepare
2. copy expected data. This process doesn't raise the errors/exceptions
3. start c-s stress command, but actually it wasn't started, just printed the command 
4. failed on is_client_encrypt:
```
< t:2020-04-25 01:44:39,683 f:common.py       l:960  c:utils                p:DEBUG > Executing CQL 'SELECT count(*) FROM cqlstress_lwt_example.blogposts_update_2_columns_lwt_indicator_expect'...
< t:2020-04-25 01:44:42,733 f:common.py       l:967  c:cassandra.cluster    p:DEBUG > Shutting down Cluster Scheduler
< t:2020-04-25 01:44:42,734 f:common.py       l:967  c:cassandra.cluster    p:DEBUG > Shutting down control connection
< t:2020-04-25 01:44:42,734 f:libevreactor.py l:287  c:cassandra.io.libevreactor p:DEBUG > Closing connection (139670501461744) to 54.166.98.203:9042
< t:2020-04-25 01:44:42,734 f:libevreactor.py l:291  c:cassandra.io.libevreactor p:DEBUG > Closed socket to 54.166.98.203:9042
< t:2020-04-25 01:44:42,734 f:libevreactor.py l:287  c:cassandra.io.libevreactor p:DEBUG > Closing connection (139670501490472) to 54.166.98.203:9042
< t:2020-04-25 01:44:42,734 f:libevreactor.py l:291  c:cassandra.io.libevreactor p:DEBUG > Closed socket to 54.166.98.203:9042
< t:2020-04-25 01:44:42,735 f:tester.py       l:1414 c:sdcm.tester          p:DEBUG > All rows have been copied from blogposts_update_2_columns_lwt_indicator to blogposts_update_2_columns_lwt_indicator_expect
< t:2020-04-25 01:44:42,769 f:longevity_test.py l:51   c:sdcm.tester          p:DEBUG > stress cmd: cassandra-stress user profile=/tmp/c-s_lwt_big_data.yaml ops'(lwt_update_one_column=1,lwt_update_two_columns=1)' cl=QUORUM duration=10m -
mode native cql3 -rate threads=50
< t:2020-04-25 01:44:42,770 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@52.5.108.199]: Running command "grep ^client_encryption_options: /etc/scylla/scylla.yaml -A 3 | grep enabled | awk '{print $2}'
"...
< t:2020-04-25 01:44:42,950 f:remote.py       l:323  c:sdcm.remote          p:ERROR > [Errno 104] Connection reset by peer
< t:2020-04-25 01:44:42,963 f:tester.py       l:1556 c:sdcm.tester          p:INFO  > TearDown is starting...
```

**Comment by roydahan** [comment] 2020-07-06 12:54
Remoter issue caused by connectivity issue probably.
closing it.
we hope the new libssh will solve such things.

**Closed by roydahan** 2020-07-06 12:54 UTC
