### ISSUE TITLE
"No results from Prometheus" error during upgrade test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5214] opened 2022-09-02 06:34 UTC
I've been trying some upgrade test in my staging, but It fails before starting upgrade steps due:
```
2022-09-01 16:24:56.829: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=b2b682e4-756b-416a-89de-1cd552036085, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 575, in test_rolling_upgrade
    self.metric_has_data(
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 3015, in metric_has_data
    is_metric_has_data()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 3011, in is_metric_has_data
    assert results, "No results from Prometheus"
AssertionError: No results from Prometheus
```
in sct log we can see such query:
```
< t:2022-09-01 16:23:08,260 f:db_stats.py     l:258  c:sdcm.db_stats        p:DEBUG > Query to PrometheusDB: http://10.4.3.54:9090/api/v1/query_range?query=gemini_cql_requests&start=1662049328.2605822&end=1662049388.2605822&step=20
< t:2022-09-01 16:23:08,267 f:db_stats.py     l:225  c:sdcm.db_stats        p:DEBUG > Response from Prometheus server: {'status': 'success', 'data': {'resultType': 'matrix', 'result': []}}
< t:2022-09-01 16:23:08,268 f:tester.py       l:3010 c:UpgradeTest          p:DEBUG > metric_has_data: []
< t:2022-09-01 16:23:08,268 f:decorators.py   l:69   c:sdcm.utils.decorators p:DEBUG > 'is_metric_has_data': failed with 'AssertionError('No results from Prometheus')', retrying [#9]
```
For various builds it fails on different query - so I doubt it is related to gemini - the stress threads are not failing.
I tried also with different base scylla versions with the same effect.
Recently on master we don't hit this issue as we fail before these verifications.

## Restore commands:
Restore Monitor Stack command: $ hydra investigate show-monitor 92b1ac12-b6f5-4f72-8961-56a56e62c040
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=92b1ac12-b6f5-4f72-8961-56a56e62c040)
Show all stored logs command: $ hydra investigate show-logs 92b1ac12-b6f5-4f72-8961-56a56e62c040

## Logs:
[grafana - https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_162501/grafana-screenshot-overview-20220901_162502-rolling-upgrade--centos-monitor-node-92b1ac12-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_162501/grafana-screenshot-overview-20220901_162502-rolling-upgrade--centos-monitor-node-92b1ac12-1.png)
[grafana - https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_162501/grafana-screenshot-rolling-multi-dc-upgrade-ami-test-staging2-scylla-per-server-metrics-nemesis-20220901_162617-rolling-upgrade--centos-monitor-node-92b1ac12-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_162501/grafana-screenshot-rolling-multi-dc-upgrade-ami-test-staging2-scylla-per-server-metrics-nemesis-20220901_162617-rolling-upgrade--centos-monitor-node-92b1ac12-1.png)
[db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_163405/db-cluster-92b1ac12.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_163405/db-cluster-92b1ac12.tar.gz)
[loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_163405/loader-set-92b1ac12.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_163405/loader-set-92b1ac12.tar.gz)
[monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_163405/monitor-set-92b1ac12.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_163405/monitor-set-92b1ac12.tar.gz)
[sct - https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_163405/sct-runner-92b1ac12.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_163405/sct-runner-92b1ac12.tar.gz)
## Links:
[Build URL](https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/rolling-multi-dc-upgrade-ami-test-staging2/45/)
[Download "Overview metrics" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_162501/grafana-screenshot-overview-20220901_162502-rolling-upgrade--centos-monitor-node-92b1ac12-1.png)
[Download "Per server metrics nemesis" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/92b1ac12-b6f5-4f72-8961-56a56e62c040/20220901_162501/grafana-screenshot-rolling-multi-dc-upgrade-ami-test-staging2-scylla-per-server-metrics-nemesis-20220901_162617-rolling-upgrade--centos-monitor-node-92b1ac12-1.png)

**Comment by fruch** [comment] 2022-09-02 11:44
@soyacz this week I've merged a PR running Gemini from docker, might be related.

I'm not sure where this specific metric is created, but the question is did Gemini even run ? could be it was failing to run ?

**Comment by fruch** [comment] 2022-09-04 06:05
@soyacz found the root cause, seem like we are scraping gemini metrics directly (and not via the test code, as we do for other tools), also in the upgrade test is the only place we actually use those metric to wait for it to start.

```python
            if self.params.get('gemini_cmd'):
                gemini_loader_targets_list = ["%s:2112" % getattr(node, self.DB_NODES_IP_ADDRESS)
                                              for node in self.targets["loaders"].nodes]
                scrape_configs.append(dict(job_name="gemini_metrics", honor_labels=True,
                                           static_configs=[dict(targets=gemini_loader_targets_list)]))
```

for now I'll open that port on the docker command. it would mean we'll fail to run multiple Gemini command at the same loader at the same time.

**Closed** 2022-09-05 09:32 UTC
