### ISSUE TITLE
Not "clear" Stderr message in error log "Stderr: already printed"

### ISSUE THREAD

**Issue by nizarh11** [scylladb/scylla-cluster-tests#2432] opened 2020-07-27 22:43 UTC
### Versions
* **SCT**: master
* **scylla**: master

### Description
I am getting a weird Stderr during a longevity run - "Stderr: already printed"

### Logs
* test_id: c050e644-3ed2-4d5e-b5a2-41ff224cd0e3
* job log: https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-10gb-3h-test/153/artifact/scylla-cluster-tests/latest/events_log/error.log

```
2020-07-27 00:12:36.208: (TestFrameworkEvent Severity.ERROR), source=LongevityTest.SetUp() 
exception=[Node longevity-10gb-3h-master-db-node-c050e644-3 [52.50.224.18 | 10.0.35.141] (seed: False)] NodeSetupFailed: Encountered a bad command exit code!

Command: 'sudo systemctl start scylla-server.service'

Exit code: 1

Stdout:



Stderr: already printed


Traceback (most recent call last):
  File "/home/jenkins/slave/workspace/scylla-master/longevity/longevity-10gb-3h-test/scylla-cluster-tests/sdcm/cluster.py", line 2963, in node_setup
    cl_inst.node_setup(_node, **setup_kwargs)
  File "/home/jenkins/slave/workspace/scylla-master/longevity/longevity-10gb-3h-test/scylla-cluster-tests/sdcm/cluster.py", line 3508, in node_setup
    node.start_scylla_server(verify_up=False)
  File "/home/jenkins/slave/workspace/scylla-master/longevity/longevity-10gb-3h-test/scylla-cluster-tests/sdcm/cluster.py", line 2346, in start_scylla_server
    self.remoter.run('sudo systemctl start scylla-server.service', timeout=timeout)
  File "/home/jenkins/slave/workspace/scylla-master/longevity/longevity-10gb-3h-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
    return func(*args, **kwargs)
  File "/home/jenkins/slave/workspace/scylla-master/longevity/longevity-10gb-3h-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 546, in run
    result = _run()
  File "/home/jenkins/slave/workspace/scylla-master/longevity/longevity-10gb-3h-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 56, in inner
    return func(*args, **kwargs)
  File "/home/jenkins/slave/workspace/scylla-master/longevity/longevity-10gb-3h-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/jenkins/slave/workspace/scylla-master/longevity/longevity-10gb-3h-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 508, in _run_execute
    result = self.connection.run(**command_kwargs)
  File "/home/jenkins/slave/workspace/scylla-master/longevity/longevity-10gb-3h-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 599, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/jenkins/slave/workspace/scylla-master/longevity/longevity-10gb-3h-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 633, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'sudo systemctl start scylla-server.service'

Exit code: 1

Stdout:



Stderr: already printed
```

**Comment by nizarh11** [comment] 2020-07-27 22:47
@roydahan @fruch @bentsi, This issue might be related to Scylla more than SCT, can you please confirm before I move it.

**Comment by roydahan** [comment] 2020-07-28 10:05
Seems to me like a scylla issue, but you need to add more information from the log.

**Comment by fruch** [comment] 2020-07-28 10:15
The already printed is a SCT issue... we solved, but seems like the libssh2 new code broke it again.

but the root cause should be looked at the node log or sct.log

**Comment by nizarh11** [comment] 2020-07-29 09:32
I already found the root cause. I am only referring to the Stderr message.

Same thing on sct.log
```
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > Command: 'sudo systemctl start scylla-server.service'
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > Exit code: 1
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > Stdout:
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > Stderr: already printed
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > Traceback (most recent call last):
< t:2020-07-27 00:12:36,221 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 
```

**Comment by dkropachev** [comment] 2020-09-30 05:53
Should be fixed by now.

**Closed by dkropachev** 2020-09-30 05:53 UTC
