### ISSUE TITLE
AuditLogTestFailure: Audit log is empty while should contain executed DDL (alter table) operation

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#7885] opened 2024-07-08 14:42 UTC
## Packages

Scylla version: `2023.1.10-20240706.21cffccc1ccd` with build-id `87fcdaf894b5dfb25d26f12d7d4aed71b84bfd44`

Kernel Version: `5.15.0-1064-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

`disrupt_toggle_audit_syslog` nemesis failed:
```
2024-07-07 04:23:41.678: (DisruptionEvent Severity.ERROR) period_type=end event_id=a962e6a1-91a9-400c-9d53-c59097c61cc7 duration=27m1s: nemesis_name=ToggleAuditSyslog target_node=Node alternator-3h-2023-1-db-node-c3cdc74e-5 [54.226.128.206 | 10.12.8.73] errors=Audit log is empty while should contain executed DDL (alter table) operation
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5088, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4819, in disrupt_toggle_audit_syslog
self._disrupt_toggle_audit(store="syslog")
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4920, in _disrupt_toggle_audit
raise AuditLogTestFailure("\n".join(errors))
sdcm.exceptions.AuditLogTestFailure: Audit log is empty while should contain executed DDL (alter table) operation
```

To find audit log in syslog we search for next condition:
https://github.com/scylladb/scylla-cluster-tests/blob/56f3ad57e7b0a2b691f33de59fbba0f342b2b4c8/sdcm/audit.py#L121

Looking in the node `messages.log` the line can be found:
```
2024-07-07T04:23:02.589+00:00 alternator-3h-2023-1-db-node-c3cdc74e-7   !NOTICE | scylla-audit[16937]: "10.12.10.63:0", "DDL", "ONE", "audit_cf", "audit_keyspace", "ALTER TABLE audit_keyspace.audit_cf WITH read_repair_chance = 0.0", "10.12.11.32:0", "anonymous", "false"
```

But in the system.log it looks not same:
```
Jul 07 04:23:02.115065 alternator-3h-2023-1-db-node-c3cdc74e-7 scylla-audit[16937]: "10.12.10.63:0", "DDL", "ONE", "audit_cf", "audit_keyspace", "ALTER TABLE audit_keyspace.audit_cf WITH read_repair_chance = 0.0", "10.12.11.32:0", "anonymous", "false"
```

Means - word "!NOTICE" is missed in the system.log.
What I did not understand - why it failed for the alter table only and not for others

Looks like this nemesis was run successfully first time:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/app/dashboards#/view/9312c960-2d8e-11eb-8579-3fa2093e3e28?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- alternator-3h-2023-1-db-node-c3cdc74e-8 (23.20.135.75 | 10.12.9.37) (shards: 14)
- alternator-3h-2023-1-db-node-c3cdc74e-7 (54.226.92.69 | 10.12.10.63) (shards: 14)
- alternator-3h-2023-1-db-node-c3cdc74e-6 (54.235.44.80 | 10.12.11.20) (shards: 14)
- alternator-3h-2023-1-db-node-c3cdc74e-5 (54.226.128.206 | 10.12.8.73) (shards: 14)
- alternator-3h-2023-1-db-node-c3cdc74e-4 (54.163.28.13 | 10.12.8.190) (shards: 14)
- alternator-3h-2023-1-db-node-c3cdc74e-3 (54.147.31.218 | 10.12.10.206) (shards: 14)
- alternator-3h-2023-1-db-node-c3cdc74e-2 (18.212.93.38 | 10.12.11.53) (shards: 14)
- alternator-3h-2023-1-db-node-c3cdc74e-1 (34.201.143.29 | 10.12.11.148) (shards: 14)

OS / Image: `ami-0d95c4087d26503dd` (aws: undefined_region)

Test: `longevity-alternator-3h-test`
Test id: `c3cdc74e-2f86-4f21-9c9b-3679792e1a97`
Test name: `enterprise-2023.1/longevity/longevity-alternator-3h-test`
Test config file(s):

- [longevity-alternator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2d1cef1f9da0f3a751daa419b2d6c078676d446e/test-cases/longevity/longevity-alternator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c3cdc74e-2f86-4f21-9c9b-3679792e1a97`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c3cdc74e-2f86-4f21-9c9b-3679792e1a97)
- Show all stored logs command: `$ hydra investigate show-logs c3cdc74e-2f86-4f21-9c9b-3679792e1a97`

## Logs:
- **db-cluster-c3cdc74e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/db-cluster-c3cdc74e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/db-cluster-c3cdc74e.tar.gz)
- **sct-runner-events-c3cdc74e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/sct-runner-events-c3cdc74e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/sct-runner-events-c3cdc74e.tar.gz)
- **sct-c3cdc74e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/sct-c3cdc74e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/sct-c3cdc74e.log.tar.gz)
- **loader-set-c3cdc74e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/loader-set-c3cdc74e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/loader-set-c3cdc74e.tar.gz)
- **monitor-set-c3cdc74e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/monitor-set-c3cdc74e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/monitor-set-c3cdc74e.tar.gz)
- **parallel-timelines-report-c3cdc74e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/parallel-timelines-report-c3cdc74e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3cdc74e-2f86-4f21-9c9b-3679792e1a97/20240707_045440/parallel-timelines-report-c3cdc74e.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-alternator-3h-test/27/)
[Argus](https://argus.scylladb.com/test/1ebc75a8-1976-412b-8aaa-38fdaecd54b7/runs?additionalRuns[]=c3cdc74e-2f86-4f21-9c9b-3679792e1a97)
</details>

**Comment by fruch** [comment] 2024-07-09 20:05
I think it might be that:
https://github.com/scylladb/scylla-cluster-tests/pull/7917

but I'm not completely sure

**Comment by soyacz** [comment] 2024-07-10 07:23
> I think it might be that: #7917
> 
> but I'm not completely sure

I don't think so - previous check worked for create table statement.
I'd presume `node.open_system_log` method doesn't work properly in some cases - doesn't jump to proper place.

**Comment by fruch** [comment] 2024-07-10 07:58
seems like it was reported before: #7102
closing a duplicate

**Closed by fruch** 2024-07-10 07:58 UTC

**Comment by soyacz** [comment] 2024-07-10 08:00
This one might give us valuable logs to further investigate the issue.

**Comment by fruch** [comment] 2024-07-10 08:26
> This one might give us valuable logs to further investigate the issue.

you have a the `test_id` of all of them in the link I've supplied in https://github.com/scylladb/scylla-cluster-tests/issues/7102

as for the timestamp I think think we shouldn't be using naive timestamps anywhere.
and yes python-driver might return such one, and it's a stupid behavior that we can change for compatibility sack
ask @k0machi how many time he got bit by it.

**Comment by juliayakovlev** [comment] 2024-07-10 08:33
@fruch @soyacz 
Are you sure that it's connected to timestamp?
As I shown in description, we are searching for 2 substrings but one of them does not exist in the system.log

```
Jul 07 04:23:02.115065 alternator-3h-2023-1-db-node-c3cdc74e-7 scylla-audit[16937]: "10.12.10.63:0", "DDL", "ONE", "audit_cf", "audit_keyspace", "ALTER TABLE audit_keyspace.audit_cf WITH read_repair_chance = 0.0", "10.12.11.32:0", "anonymous", "false"
```
Or I miss something?

**Comment by fruch** [comment] 2024-07-10 08:40
> @fruch @soyacz Are you sure that it's connected to timestamp? As I shown in description, we are searching for 2 substrings but one of them does not exist in the system.log
> 
> ```
> Jul 07 04:23:02.115065 alternator-3h-2023-1-db-node-c3cdc74e-7 scylla-audit[16937]: "10.12.10.63:0", "DDL", "ONE", "audit_cf", "audit_keyspace", "ALTER TABLE audit_keyspace.audit_cf WITH read_repair_chance = 0.0", "10.12.11.32:0", "anonymous", "false"
> ```
> 
> Or I miss something?

those two different logs coming from 2 different places, one is coming via syslong-ng during the test (one we care about), other is when the test end, we pick up all of the log via `journalctl` command, and that one by default doesn't have levels, i,e, NOTICE

if that was the problem no check was working, but in this case, only on check failed out  multiple ones

so that not the root cause.

and I'm not sure the utc timestamp is the root cause

it's might be that we have > < in there, while we drop the nanosec/milisec, and we might missing it by a second.

it's hard to tell, since there no print of the timestamps being use for the compare.

so I think the  only think is to add a bit of debug print there
