### ISSUE TITLE
No attribute or config key found for 'gateway'

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#2187] opened 2020-05-26 04:34 UTC
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-4.1
* **scylla**: scylla 4.1.rc0

### Logs
* test_id: 0e5b4b3a-e13d-48b7-b035-3d438dd48aa6
* job log: https://storage.cloud.google.com/upload.scylladb.com/amos/sct/issue_2187/events_log.tar.gz?authuser=0

### Description

Not sure if this error is harmful or not.

```
2020-05-25 09:37:46.622: (ThreadFailedEvent Severity.ERROR): message=No attribute or config key found for 'gateway'

Valid keys: []

Valid real attributes: ['clear', 'clone', 'env_prefix', 'file_prefix', 'from_data', 'from_v1', 'global_defaults', 'load_base_conf_files', 'load_collection', 'load_defaults', 'load_overrides', 'load_project', 'load_runtime', 'load_shell_env', 'load_ssh_config', 'load_system', 'load_user', 'merge', 'pop', 'popitem', 'prefix', 'set_project_location', 'set_runtime_path', 'set_runtime_ssh_path', 'setdefault', 'update']
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/invoke/config.py", line 111, in __getattr__
    return self._get(key)
  File "/usr/local/lib/python3.6/site-packages/invoke/config.py", line 176, in _get
    value = self._config[key]
KeyError: 'gateway'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sct/sdcm/utils/thread.py", line 24, in wrapper
    result = func(*args, **kwargs)
  File "/sct/sdcm/cluster.py", line 1009, in backtrace_thread
    self.get_backtraces()
  File "/sct/sdcm/cluster.py", line 957, in get_backtraces
    core_pids = self._get_core_pids()
  File "/sct/sdcm/utils/decorators.py", line 123, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/cluster.py", line 973, in _get_core_pids
    verbose=False, ignore_status=True, new_session=True)
  File "/sct/sdcm/utils/decorators.py", line 123, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 333, in run
    result = _run()
  File "/sct/sdcm/utils/decorators.py", line 118, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 315, in _run
    with self._create_connection() as connection:
  File "/sct/sdcm/remote.py", line 271, in _create_connection
    connect_kwargs=self.connect_config)
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 423, in __init__
    self.gateway = gateway if gateway is not None else self.get_gateway()
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 524, in get_gateway
    return self.config.gateway
  File "/usr/local/lib/python3.6/site-packages/invoke/config.py", line 123, in __getattr__
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'gateway'

Valid keys: []

Valid real attributes: ['clear', 'clone', 'env_prefix', 'file_prefix', 'from_data', 'from_v1', 'global_defaults', 'load_base_conf_files', 'load_collection', 'load_defaults', 'load_overrides', 'load_project', 'load_runtime', 'load_shell_env', 'load_ssh_config', 'load_system', 'load_user', 'merge', 'pop', 'popitem', 'prefix', 'set_project_location', 'set_runtime_path', 'set_runtime_ssh_path', 'setdefault', 'update']
```

### Steps to Reproduce

I seem this error many times in https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/longevity/job/longevity-2tb-4days-1Dis-2NonDis-Nemesises/2

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

AttributeError: No attribute or config key found for 'gateway'

/CC @bentsi @aleksbykov @fruch

**Comment by fruch** [comment] 2020-05-26 05:31
@dkropachev I think we should make sure each thread would have it's own connection...
cause I think this is cause by a failure in a different thread, and the fabric connection isn't thread safe...

**Comment by amoskong** [comment] 2020-06-30 08:50
This issue occurred in the following jobs:

- https://jenkins.scylladb.com/job/scylla-4.1/view/4.1-test/job/longevity/job/longevity-lwt-1loader-3h/2
- https://jenkins.scylladb.com/job/scylla-4.1/view/4.1-test/job/longevity/job/longevity-alternator-3h-multidc-test/2
- https://jenkins.scylladb.com/job/scylla-4.1/view/4.1-test/job/longevity/job/longevity-alternator-200gb-48h/2

When the issue occurred, the job failed or stuck until abort.

/CC @roydahan

**Comment by roydahan** [comment] 2020-06-30 09:17
@fruch / @dkropachev / @bentsi , what is special in these jobs that they hit this issue?
I don't understand where it comes from.

**Comment by fruch** [comment] 2020-06-30 09:34
this looks like we running out of CPU on the worker, cause of other prints. 
I don't know why exactly, I don't think those jobs has something special on their own

**Comment by yarongilor** [comment] 2020-07-23 10:08
reproduced in cloud performance latency test:
https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/cloud_performance_latency_test/5/execution/node/68/log/?consoleFull
```
21:54:45  ----- LAST ERROR EVENT ---------------------------------------------------------
21:54:45  2020-07-22 13:44:48.828: (ThreadFailedEvent Severity.ERROR): message=No attribute or config key found for 'gateway'
21:54:45  Valid keys: []
21:54:45  Valid real attributes: ['clear', 'clone', 'env_prefix', 'file_prefix', 'from_data', 'from_v1', 'global_defaults', 'load_base_conf_files', 'load_collection', 'load_defaults', 'load_overrides', 'load_project', 'load_runtime', 'load_shell_env', 'load_ssh_config', 'load_system', 'load_user', 'merge', 'pop', 'popitem', 'prefix', 'set_project_location', 'set_runtime_path', 'set_runtime_ssh_path', 'setdefault', 'update']
21:54:45  Traceback (most recent call last):
21:54:45  File "/usr/local/lib/python3.8/site-packages/invoke/config.py", line 111, in __getattr__
21:54:45  return self._get(key)
21:54:45  File "/usr/local/lib/python3.8/site-packages/invoke/config.py", line 176, in _get
21:54:45  value = self._config[key]
21:54:45  KeyError: 'gateway'
21:54:45  During handling of the above exception, another exception occurred:
21:54:45  Traceback (most recent call last):
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/sct_events.py", line 1057, in wrapper
21:54:45  result = func(*args, **kwargs)
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/cluster.py", line 1022, in backtrace_thread
21:54:45  self.get_backtraces()
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/cluster.py", line 970, in get_backtraces
21:54:45  core_pids = self._get_core_pids()
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
21:54:45  return func(*args, **kwargs)
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/cluster.py", line 985, in _get_core_pids
21:54:45  result = self.remoter.run('sudo coredumpctl --no-pager --no-legend 2>&1',
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
21:54:45  return func(*args, **kwargs)
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 546, in run
21:54:45  result = _run()
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/utils/decorators.py", line 56, in inner
21:54:45  return func(*args, **kwargs)
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run
21:54:45  return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 505, in _run_execute
21:54:45  with self._create_connection() as connection:
21:54:45  File "/home/jenkins/slave/workspace/scylla-staging/Longevity_yaron/cloud_performance_latency_test/scylla-cluster-tests/sdcm/remote/remote_cmd_runner.py", line 118, in _create_connection
21:54:45  return Connection(
21:54:45  File "/usr/local/lib/python3.8/site-packages/fabric/connection.py", line 423, in __init__
21:54:45  self.gateway = gateway if gateway is not None else self.get_gateway()
21:54:45  File "/usr/local/lib/python3.8/site-packages/fabric/connection.py", line 524, in get_gateway
21:54:45  return self.config.gateway
21:54:45  File "/usr/local/lib/python3.8/site-packages/invoke/config.py", line 123, in __getattr__
21:54:45  raise AttributeError(err)
21:54:45  AttributeError: No attribute or config key found for 'gateway'
21:54:45  Valid keys: []
21:54:45  Valid real attributes: ['clear', 'clone', 'env_prefix', 'file_prefix', 'from_data', 'from_v1', 'global_defaults', 'load_base_conf_files', 'load_collection', 'load_defaults', 'load_overrides', 'load_project', 'load_runtime', 'load_shell_env', 'load_ssh_config', 'load_system', 'load_user', 'merge', 'pop', 'popitem', 'prefix', 'set_project_location', 'set_runtime_path', 'set_runtime_ssh_path', 'setdefault', 'update']
21:54:45  ----- LAST WARNING EVENT -------------------------------------------------------
```

**Comment by yarongilor** [comment] 2020-07-23 10:12
why is this issue blocked by a PR that is already merged?
if this PR addressed the issue - why is it reproduced now on master?

**Comment by amoskong** [comment] 2020-07-24 01:42
> why is this issue blocked by a PR that is already merged?

What's the PR number?

> if this PR addressed the issue - why is it reproduced now on master?

**Comment by dkropachev** [comment] 2020-07-24 12:30
Addressed in here - https://github.com/scylladb/scylla-cluster-tests/pull/2422

**Closed** 2020-08-11 08:48 UTC
