### ISSUE TITLE
[k8s] Replace of ip address during `disrupt_grow_shrink_cluster`, fails healhcheck

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5442] opened 2022-11-21 06:53 UTC
## Installation details

Kernel Version: 5.4.219-126.411.amzn2.x86_64
Scylla version (or git commit hash): `5.2.0~dev-20221118.a396c27efccd` with build-id `74a707956a4aba54865b70d78b830b666f5f19f7`

Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-3h-eks`
Test id: `26d964b4-2a0e-4283-bae9-5f1930a711c7`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-eks`
Test config file(s):

- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f31573efeb1cbd00bb3c321995dbcc8c428df4f2/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)

## Issue description

after `disrupt_grow_shrink_cluster` has run and of of the pods changed it's ip address along the way, we are this failure:
```
2022-11-20 04:03:26.567: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=0f01e674-6d6b-490f-8250-8cc7c3d1ceac: type=NodeStatus node=sct-cluster-us-east1-b-us-east1-0 error=Current node Node sct-cluster-us-east1-b-us-east1-0 [10.0.3.150 | 10.0.1.114] (seed: False). The node Node sct-cluster-us-east1-b-us-east1-0 [10.0.3.150 | 10.0.1.114] (seed: False) exists in the gossip but doesn't exist in the nodetool.status
```

seems like the hack we have in `get_nodetool_status`:
```
                # NOTE: following replacement is needed for the K8S case where
                #       registered IP is different than the one used for network connections
                if verification_node.is_kubernetes():
                    for node in self.nodes:
                        if node_ip in node.get_all_ip_addresses() and node_ip != node.ip_address:
                            node_ip = node.ip_address
```
kind of contradict the mapping to Node objects done in `get_nodes_status`

- Restore Monitor Stack command: `$ hydra investigate show-monitor 26d964b4-2a0e-4283-bae9-5f1930a711c7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=26d964b4-2a0e-4283-bae9-5f1930a711c7)
- Show all stored logs command: `$ hydra investigate show-logs 26d964b4-2a0e-4283-bae9-5f1930a711c7`

## Logs:
- **db-cluster-26d964b4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/db-cluster-26d964b4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/db-cluster-26d964b4.tar.gz)
- **monitor-set-26d964b4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/monitor-set-26d964b4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/monitor-set-26d964b4.tar.gz)
- **loader-set-26d964b4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/loader-set-26d964b4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/loader-set-26d964b4.tar.gz)
- **sct-runner-26d964b4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/sct-runner-26d964b4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/sct-runner-26d964b4.tar.gz)
- **parallel-timelines-report-26d964b4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/parallel-timelines-report-26d964b4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/parallel-timelines-report-26d964b4.tar.gz)
- **kubernetes-26d964b4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/kubernetes-26d964b4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/26d964b4-2a0e-4283-bae9-5f1930a711c7/20221120_041843/kubernetes-26d964b4.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks/35/)

**Comment by vponomaryov** [comment] 2022-11-26 19:38
This is related to the existing following SCT bug: https://github.com/scylladb/scylla-cluster-tests/issues/5467
I am working on the solution for the automatic update of the IP mapping.
Already have the design, implementation is in progress...

**Comment by fruch** [comment] 2022-11-29 06:00
> This is related to the existing following SCT bug: https://github.com/scylladb/scylla-cluster-tests/issues/5467
> I am working on the solution for the automatic update of the Scylla pods IP mapping and monitorings.
> Already have the design, implementation is in progress...

Please next time, write a few lines on the design, before/after rushing into implementing it

> 
> Considering this one as high priority because in my latest K8S multitenant test run with 14 clients [1] and nemesis's the problem of not caught Scylla pods IP changes became a mess.
> [1] https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-12h-multitenant-eks/9/consoleFull

**Comment by vponomaryov** [comment] 2022-12-03 12:18
https://github.com/scylladb/scylla-cluster-tests/pull/5515

**Comment by vponomaryov** [comment] 2022-12-13 17:09
Closing it because the fix has already been merged here: https://github.com/scylladb/scylla-cluster-tests/pull/5515
Reopen if it gets reproduced.

**Closed by vponomaryov** 2022-12-13 17:09 UTC
Labels: scylla-operator
