### ISSUE TITLE
[Azure] NIC Not Found

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#7388] opened 2024-05-02 07:09 UTC
one of provision tests in a specific PR, failed, not finding the NIC that was created: 
```
2024-05-01T18:23:53.343Z] sdcm.provision.provisioner.ProvisionError: (NotFound) Resource /subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCT-56d78227-2d63-4519-af3b-8817bb2aed30-eastus/providers/Microsoft.Network/networkInterfaces/pr-provision-test-pr-7305-db-node-eastus-3-nic not found.

[2024-05-01T18:23:53.343Z] Code: NotFound

[2024-05-01T18:23:53.343Z] Message: Resource /subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCT-56d78227-2d63-4519-af3b-8817bb2aed30-eastus/providers/Microsoft.Network/networkInterfaces/pr-provision-test-pr-7305-db-node-eastus-3-nic not found.
```

seem like before we had this `OperationPreempted` that we are not raising:

```
[2024-05-01T18:23:46.521Z] < t:2024-05-01 18:23:36,520 f:virtual_machine_provider.py l:118  c:sdcm.provision.azure.virtual_machine_provider p:ERROR > Error when waiting for VM pr-provision-test-pr-7305-db-node-eastus-1: (OperationPreempted) Operation execution has been preempted by a more recent operation.

[2024-05-01T18:23:46.521Z] < t:2024-05-01 18:23:36,520 f:virtual_machine_provider.py l:118  c:sdcm.provision.azure.virtual_machine_provider p:ERROR > Code: OperationPreempted

[2024-05-01T18:23:46.521Z] < t:2024-05-01 18:23:36,520 f:virtual_machine_provider.py l:118  c:sdcm.provision.azure.virtual_machine_provider p:ERROR > Message: Operation execution has been preempted by a more recent 
```

so we got preemption of some kind, that we don't progorate clearly 

Logs:
https://jenkins.scylladb.com/blue/organizations/jenkins/sct-github-PRs-scan%2Fscylla-cluster-tests/detail/PR-7305/17/pipeline
test_id: 56d78227-2d63-4519-af3b-8817bb2aed30

**Comment by fruch** [comment] 2024-05-02 07:09
@soyacz have you seen something like that ?

**Comment by soyacz** [comment] 2024-05-05 05:59
looks like a duplicate of https://github.com/scylladb/scylla-cluster-tests/issues/5198

**Closed** 2024-05-05 10:26 UTC
Labels: Azure
