### ISSUE TITLE
TestAbortedError: Test aborted unexpectedly

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#649] opened 2018-10-12 03:58 UTC
Example 1:
http://jenkins.cloudius-systems.com:8080/job/scylla-staging-scale-cluster-test-clone-amos/18/label=aws-scylla-qa-builder1/console

```
06:49:39 ERROR 1-grow_cluster_test.py:GrowClusterTest.test_grow_x_to_y -> TestAbortedError: Test aborted unexpectedly
```
The cluster grows to 107 nodes (base cluster size is 50), then avocado abort.

Example 2:
Roy executed a job from cmdline in aws-builder1,  The cluster grows to 180 nodes (base cluster size is 180), job abort during monitor setup.

Example 3:
I executed a job from cmdline in aws-builder1,  The cluster grows to 200 nodes (base cluster size is 200), job abort during monitor setup.

I didn't OOM msg in dmesg of aws-builder1.

/CC @roydahan @bentsi

**Comment by bentsi** [comment] 2018-10-12 13:37
@amoskong 
1. Before opening a ticket, please investigate the issue and try to find a root cause  and not just look on last lines of the log and conclude that something wrong!!!
2. Try to find out why the job is aborted. My gut feeling is that we are out of RAM due to a huge cluster that produces tons of logs. (Monitor RAM usage on the build server during the job run)

**Comment by amoskong** [comment] 2018-10-15 04:55
On Fri, Oct 12, 2018 at 9:23 PM, Bentsi <notifications@github.com> wrote:

> Answers :
> 1.
> http://jenkins.cloudius-systems.com:8080/job/scylla-
> staging-scale-cluster-test-clone-amos/18/label=aws-
> scylla-qa-builder1/console
>
> 0,       0,       0,       0
> 01:49:39 ERROR 1-grow_cluster_test.py:GrowClusterTest.test_grow_x_to_y -> TestAbortedError: Test aborted unexpectedly
> 01:51:29 Not logging /proc/slabinfo (lack of permissions)
> 01:51:30 Build step 'Conditional steps (multiple)' marked build as failure
> 01:51:30 $ ssh-agent -k
> 01:51:31 unset SSH_AUTH_SOCK;
> 01:51:31 unset SSH_AGENT_PID;
> 01:51:31 echo Agent pid 14247 killed;
> 01:51:31 [ssh-agent] Stopped.
> 01:51:31 Archiving artifacts
> 01:52:13 Recording test results
> 01:52:17 ERROR: Step ‘Publish JUnit test result report’ aborted due to exception:
> 01:52:17 java.lang.OutOfMemoryError: Java heap space
> 01:52:17 	at java.util.Arrays.copyOf(Arrays.java:3332)
> 01:52:17 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
> 01:52:17 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
>
> *One can clearly see java.lang.OutOfMemoryError: Java heap space that
> means Jenkins slave was out of memory, probably due to long log,*
>
Avocado test Aborted at 01:49:39, then jenkins touched another OOM after 2+
mins. The agent was stopped, not sure if the OOM was from jenkins master or
slaver.

In some old jobs, when Jenkins is crash, the avocado process can still
running without effect. I thought the avocado abort wasn't caused by
jenkins oom.

>
> *nothing related to the monitor setup!*
>
Both issue subject and example 1 didn't mention `monitor setup`.


> *BTW: in the log you can see seastar_memory - oversized allocation:
> 1970176 bytes stacktraces*
>
Avocado process is running in SCT builder,  the seastart memory waring is
from db nodes, it can't directly effect avocado main process.
I also see seastar memory warning in other jobs, it won't break the whole
test (avocado process)


>    1.
>
>
> *Failed during the test when parsed Cassandra Stress errors (probably due
> to new Cassandra Stress)*
>
> 2018-10-12 05:08:28,684 remote           L0194 DEBUG| [18.212.141.237] [stdout] Results:
> 2018-10-12 05:08:28,685 remote           L0194 DEBUG| [18.212.141.237] [stdout] Op rate                   :    9,152 op/s  [READ: 9,152 op/s]
> 2018-10-12 05:08:28,685 remote           L0194 DEBUG| [18.212.141.237] [stdout] Partition rate            :    9,152 pk/s  [READ: 9,152 pk/s]
> 2018-10-12 05:08:28,685 remote           L0194 DEBUG| [18.212.141.237] [stdout] Row rate                  :    9,152 row/s [READ: 9,152 row/s]
> 2018-10-12 05:08:28,685 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency mean              :   54.5 ms [READ: 54.5 ms]
> 2018-10-12 05:08:28,686 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency median            :    0.9 ms [READ: 0.9 ms]
> 2018-10-12 05:08:28,686 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency 95th percentile   :   58.6 ms [READ: 58.6 ms]
> 2018-10-12 05:08:28,686 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency 99th percentile   : 2533.4 ms [READ: 2,533.4 ms]
> 2018-10-12 05:08:28,686 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency 99.9th percentile : 2617.2 ms [READ: 2,617.2 ms]
> 2018-10-12 05:08:28,686 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency max               : 3143.6 ms [READ: 3,143.6 ms]
> 2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total partitions          :  5,515,602 [READ: 5,515,602]
> 2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total errors              :          0 [READ: 0]
> 2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total GC count            : 0
> 2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total GC memory           : 0.000 KiB
> 2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total GC time             :    0.0 seconds
> 2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Avg GC time               :    NaN ms
> 2018-10-12 05:08:28,688 remote           L0194 DEBUG| [18.212.141.237] [stdout] StdDev GC time            :    0.0 ms
> 2018-10-12 05:08:28,688 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total operation time      : 00:10:02
> 2018-10-12 05:08:28,688 remote           L0194 DEBUG| [18.212.141.237] [stdout]
> 2018-10-12 05:08:28,688 remote           L0194 DEBUG| [18.212.141.237] [stdout] END
> 2018-10-12 05:08:30,950 remote           L0194 DEBUG| [18.212.141.237] [stderr] /home/centos/run_cassandra_stress.sh: line 1:  6567 Done                    cat /tmp/cs_
> read_pipe_$1_$2
> 2018-10-12 05:08:30,951 remote           L0194 DEBUG| [18.212.141.237] [stderr]       6568 Terminated              | python /usr/bin/cassandra_stress_exporter read
> 2018-10-12 05:08:30,954 tester           L0130 ERROR| Exception in run_stress. Will clean resources
> Traceback (most recent call last):
>   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/tester.py", line 128, in wrapper
>     return method(*args, **kwargs)
>   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/tester.py", line 662, in run_stress
>     self.verify_stress_thread(stress_queue)
>   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/tester.py", line 699, in verify_stress_thread
>     results, errors = self.loaders.verify_stress_thread(queue, self.db_cluster)
>   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/cluster.py", line 2140, in verify_stress_thread
>     node_cs_res = self._parse_cs_summary(lines)
>   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/cluster.py", line 2014, in _parse_cs_summary
>     split_idx = line.index(':')
> ValueError: substring not found
> 2018-10-12 05:08:30,956 tester           L0988 DEBUG| Cleaning up resources used in the test
>
>
Sorry for not mentioning the job name (I can find it by base cluster size
;-), I was in hurry to have lunch at that time.
I'm not talking this job, it's not avocado abort.
The example is job-2018-10-11T23.27-7f0153c/job.log  (you replied after my
example 3)

I didn't find my real example 3, it really occurred (avocado abort during
monitor setup, believe in me :-).  The log was removed by
http://jenkins.cloudius-systems.com:8080/job/scylla-staging-scale-cluster-test-clone-amos/label=aws-scylla-qa-builder1/21/
I submitted job 21, when example 3 was running (submitted from cmdline.)


>    1.
>
> *Job was aborted during docker pull when installing Grafana*
>

In this example, I still didn't know if Avocado crash is caused by monitor
setup, even it occurred at same time.


> 2018-10-12 01:13:20,287 remote           L0194 DEBUG| [18.208.172.148] [stderr] Trying to pull repository docker.io/grafana/grafana ...
> 2018-10-12 01:13:20,524 remote           L0194 DEBUG| [18.208.172.148] [stderr] 4.6.3: Pulling from docker.io/grafana/grafana
> 2018-10-12 <http://docker.io/grafana/grafana2018-10-12> 01:13:20,525 remote           L0194 DEBUG| [18.208.172.148] [stderr] c6b13209f43b: Pulling fs layer
> 2018-10-12 01:13:20,525 remote           L0194 DEBUG| [18.208.172.148] [stderr] a3ed95caeb02: Pulling fs layer
> 2018-10-12 01:13:20,525 remote           L0194 DEBUG| [18.208.172.148] [stderr] 051738ac6f7e: Pulling fs layer
> 2018-10-12 01:13:20,525 remote           L0194 DEBUG| [18.208.172.148] [stderr] 66e042ba6513: Pulling fs layer
> 2018-10-12 01:13:20,526 remote           L0194 DEBUG| [18.208.172.148] [stderr] 66e042ba6513: Waiting
> 2018-10-12 01:13:20,675 remote           L0194 DEBUG| [18.208.172.148] [stderr] a3ed95caeb02: Verifying Checksum
> 2018-10-12 01:13:20,676 remote           L0194 DEBUG| [18.208.172.148] [stderr] a3ed95caeb02: Download complete
> 2018-10-12 01:13:20,795 remote           L0194 DEBUG| [18.208.172.148] [stderr] 66e042ba6513: Verifying Checksum
> 2018-10-12 01:13:20,796 remote           L0194 DEBUG| [18.208.172.148] [stderr] 66e042ba6513: Download complete
> 2018-10-12 01:13:27,252 remote           L0194 DEBUG| [18.208.172.148] [stderr] c6b13209f43b: Verifying Checksum
> 2018-10-12 01:13:27,896 remote           L0194 DEBUG| [18.208.172.148] [stderr] c6b13209f43b: Download complete
> 2018-10-12 01:13:30,115 remote           L0194 DEBUG| [18.208.172.148] [stderr] 051738ac6f7e: Verifying Checksum
> 2018-10-12 01:13:30,421 remote           L0194 DEBUG| [18.208.172.148] [stderr] 051738ac6f7e: Download complete
> 2018-10-12 01:13:32,715 runner           L0176 ERROR| ERROR 1-grow_cluster_test.py:GrowClusterTest.test_grow_x_to_y -> TestAbortedError: Test aborted unexpectedly
> 2018-10-12 01:15:09,539 sysinfo          L0104 DEBUG| Not logging /proc/slabinfo (lack of permissions)
>
>
I created this issue to collect related information together, and track the
problem.
I investigated some avocado core code , didn't found any clue.
https://github.com/avocado-framework/avocado/blob/master/avocado/core/runner.py#L423

**Comment by amoskong** [comment] 2018-10-15 05:01
On Fri, Oct 12, 2018 at 9:37 PM, Bentsi <notifications@github.com> wrote:

> @amoskong <https://github.com/amoskong>
>
>    1. Before opening a ticket, please investigate the issue and try to
>    find a root cause and not just look on last lines of the log and conclude
>    that something wrong!!!
>
>

>
>    1. Try to find out why the job is aborted. My gut feeling is that we
>    are out of RAM due to a huge cluster that produces tons of logs. (Monitor
>    RAM usage on the build server during the job run)
>
> 99.99% is related with builder's memory usage.

I will try to not direct debug message to stdout of Avocado cmdline as we
did for longevity test jobs.
  avocado --show avocado.test:info ....

--------
I just found we didn't set swap for aws-builder1, aws-builder2,
gce-builder1-qavpc, gce-builder2-qavpc, gce-builder3-qavpc.
We set it for some old builders.  I will add swap for them now.

**Comment by bentsi** [comment] 2018-10-15 10:03
Thanks @amoskong. From recent email from you I saw that the issue could be because swap was not configured  on all the  builders. Let's close this issue and reopen if the problem occurs again.

**Closed** 2018-10-15 10:07 UTC
