### ISSUE TITLE
Node failed to run because of  X.509 certificate error

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-cluster-tests#9133] opened 2024-11-05 09:53 UTC
Test: https://jenkins.scylladb.com/job/scylla-staging/job/amnon/job/longevity-100gb-4h-test/9/ failed

The reason, a node failed with the following error:
11:26:16  2024-11-05T09:20:31.616+00:00 longevity-100gb-4h-allow-pr-db-node-9fdeb40d-5      !ERR | scylla[6924]:  [shard  0:main] init - Startup failed: std::system_error (error GnuTLS:-62, Unknown Subject Alternative name in X.509 certificate.)

**Comment by fruch** [comment] 2024-11-12 08:30
@dimakr 

do we have enough logs to investigate this one ? 

i.e. printout of each certificate ? to see what we have missing here, and why ?

if not we should introduce those kind of logs, for catching this next time.

**Comment by dimakr** [comment] 2024-11-15 09:53
The reason for the issue is known and the fix https://github.com/scylladb/scylla-cluster-tests/pull/8066 addresses it. But the test was executed from the branch `allow_protobu` of the https://github.com/amnonh/scylla-cluster-tests SC fork, which misses the fix - the fix was merged on Jul 22 and the branch was synced with upstream on Jul 10.

But to facilitate certificates related issues analysis the PR https://github.com/scylladb/scylla-cluster-tests/pull/9219 introduces a change, so that TLS/SSL artifacts created during a test are collected (and published to Argus).

**Closed** 2024-11-21 09:59 UTC
