### ISSUE TITLE
Azure (hard) reboot request takes 18 minutes to be executed

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#5608] opened 2022-12-28 14:33 UTC
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Description

At `2022-12-19 12:12:31.538` a RebuildStreamingErr nemesis has started on node 2. After the rebuild starts:
```
2022-12-19T12:14:29+00:00 longevity-10gb-3h-master-db-node-eastus-2     !INFO | scylla[48672]:  [shard 0] range_streamer - Rebuild starts, nr_ranges_remaining=4288
```
We reboot the node: https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/nemesis.py#L3320, https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/nemesis.py#L3181
At first we see that we indeed see the uptime check, and the reboot starts:
```
< t:2022-12-19 12:14:30,622 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "uptime -s"...
< t:2022-12-19 12:14:31,202 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022-12-19 08:23:02
< t:2022-12-19 12:14:31,203 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "uptime -s" finished with status 0
< t:2022-12-19 12:14:31,209 f:cluster.py      l:1008 c:sdcm.cluster_azure   p:DEBUG > Node longevity-10gb-3h-master-db-node-763ea095-eastus-2 [20.102.50.246 | 10.0.0.6] (seed: False): Hardly rebooting node
```
The Azure reboot function print a very specific info message that help identify that the azure request specifically took a while:
https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/cluster_azure.py#L118
...
https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/provision/azure/virtual_machine_provider.py#L142

From the sct log:
```
< t:2022-12-19 12:14:31,775 f:virtual_machine_provider.py l:146  c:sdcm.provision.azure.virtual_machine_provider p:INFO  > Waiting for reboot of instance: longevity-10gb-3h-master-db-node-eastus-2...
...
< t:2022-12-19 12:32:36,010 f:virtual_machine_provider.py l:148  c:sdcm.provision.azure.virtual_machine_provider p:INFO  > Instance longevity-10gb-3h-master-db-node-eastus-2 has been rebooted.
```
You can see it took ~18 minutes for the instance to be (hard) rebooted. You can see that the node started up only at that time as well:
```
2022-12-19T12:32:39+00:00 longevity-10gb-3h-master-db-node-eastus-2   !NOTICE | syslog-ng[681]: syslog-ng starting up; version='3.25.1'
```

This caused the nemesis to timeout:
```
2022-12-19 12:22:26.661: (DisruptionEvent Severity.ERROR) period_type=end event_id=4b873514-c9d5-4924-a74d-ad0c74e757c9 duration=9m55s: nemesis_name=RebuildStreamingErr target_node=Node longevity-10gb-3h-master-db-node-763ea095-eastus-2 [20.102.50.246 | 10.0.0.6] (seed: False) errors=when running on: [functools.partial(<bound method BaseNode.run_nodetool of <sdcm.cluster_azure.AzureNode object at 0x7f99745120e0>>, sub_cmd='rebuild', warning_event_on_exception=(<class 'Exception'>,), retry=0), functools.partial(<bound method Nemesis._call_disrupt_func_after_expression_logged of <sdcm.nemesis.SisyphusMonkey object at 0x7f9974256740>>, expression='Rebuild starts', disrupt_func=<bound method Nemesis.reboot_node of <sdcm.nemesis.SisyphusMonkey object at 0x7f9974256740>>, disrupt_func_kwargs={'target_node': <sdcm.cluster_azure.AzureNode object at 0x7f99745120e0>, 'hard': True, 'verify_ssh': True}, timeout=400, delay=1)]
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3832, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3334, in disrupt_rebuild_streaming_err
    self.start_and_interrupt_rebuild_streaming()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3312, in start_and_interrupt_rebuild_streaming
    ParallelObject(objects=[trigger, watcher], timeout=timeout + 60).call_objects()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 456, in call_objects
    return self.run(lambda x: x(), ignore_exceptions=ignore_exceptions)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 432, in run
    raise FuturesTimeoutError("when running on: %s" % [r.obj for r in results])
concurrent.futures._base.TimeoutError: when running on: [functools.partial(<bound method BaseNode.run_nodetool of <sdcm.cluster_azure.AzureNode object at 0x7f99745120e0>>, sub_cmd='rebuild', warning_event_on_exception=(<class 'Exception'>,), retry=0), functools.partial(<bound method Nemesis._call_disrupt_func_after_expression_logged of <sdcm.nemesis.SisyphusMonkey object at 0x7f9974256740>>, expression='Rebuild starts', disrupt_func=<bound method Nemesis.reboot_node of <sdcm.nemesis.SisyphusMonkey object at 0x7f9974256740>>, disrupt_func_kwargs={'target_node': <sdcm.cluster_azure.AzureNode object at 0x7f99745120e0>, 'hard': True, 'verify_ssh': True}, timeout=400, delay=1)]
```

## Installation details

Kernel Version: 5.15.0-1029-azure
Scylla version (or git commit hash): `5.2.0~dev-20221219.7c7eb81a6693` with build-id `c599d787c2a559492bdee4355d83c07d15365ed9`

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-763ea095-eastus-8 (52.142.49.228 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-763ea095-eastus-7 (20.228.165.188 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-763ea095-eastus-6 (20.102.51.74 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-763ea095-eastus-5 (20.102.51.24 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-763ea095-eastus-4 (20.102.50.218 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-763ea095-eastus-3 (20.102.50.217 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-763ea095-eastus-2 (20.102.50.246 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-763ea095-eastus-1 (20.102.48.136 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.2.0-dev-x86_64-2022-12-19T10-07-57` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `763ea095-1ec5-43fa-912f-72b503808db6`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/892a54f2e802c9189be1cdf55cf18d2f4d2f84d4/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 763ea095-1ec5-43fa-912f-72b503808db6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=763ea095-1ec5-43fa-912f-72b503808db6)
- Show all stored logs command: `$ hydra investigate show-logs 763ea095-1ec5-43fa-912f-72b503808db6`

## Logs:
- **db-cluster-763ea095.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/763ea095-1ec5-43fa-912f-72b503808db6/20221219_131655/db-cluster-763ea095.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/763ea095-1ec5-43fa-912f-72b503808db6/20221219_131655/db-cluster-763ea095.tar.gz)
- **sct-runner-763ea095.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/763ea095-1ec5-43fa-912f-72b503808db6/20221219_131655/sct-runner-763ea095.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/763ea095-1ec5-43fa-912f-72b503808db6/20221219_131655/sct-runner-763ea095.tar.gz)
- **monitor-set-763ea095.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/763ea095-1ec5-43fa-912f-72b503808db6/20221219_131655/monitor-set-763ea095.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/763ea095-1ec5-43fa-912f-72b503808db6/20221219_131655/monitor-set-763ea095.tar.gz)
- **loader-set-763ea095.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/763ea095-1ec5-43fa-912f-72b503808db6/20221219_131655/loader-set-763ea095.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/763ea095-1ec5-43fa-912f-72b503808db6/20221219_131655/loader-set-763ea095.tar.gz)
- **parallel-timelines-report-763ea095.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/763ea095-1ec5-43fa-912f-72b503808db6/20221219_131655/parallel-timelines-report-763ea095.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/763ea095-1ec5-43fa-912f-72b503808db6/20221219_131655/parallel-timelines-report-763ea095.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/147/)
</details>

**Comment by fruch** [comment] 2022-12-28 14:38
@ShlomiBalalis can you explain a bit, what the issue affect ? i.e. it took 18min (lets a assume it's Azure cloud issue), did it break anything in our test, timeouted or something like that ?

**Comment by ShlomiBalalis** [comment] 2022-12-28 15:39
@fruch Yes, forgot to add:
It caused the rebuild_streaming_err nemesis to time out:
```
2022-12-19 12:22:26.661: (DisruptionEvent Severity.ERROR) period_type=end event_id=4b873514-c9d5-4924-a74d-ad0c74e757c9 duration=9m55s: nemesis_name=RebuildStreamingErr target_node=Node longevity-10gb-3h-master-db-node-763ea095-eastus-2 [20.102.50.246 | 10.0.0.6] (seed: False) errors=when running on: [functools.partial(<bound method BaseNode.run_nodetool of <sdcm.cluster_azure.AzureNode object at 0x7f99745120e0>>, sub_cmd='rebuild', warning_event_on_exception=(<class 'Exception'>,), retry=0), functools.partial(<bound method Nemesis._call_disrupt_func_after_expression_logged of <sdcm.nemesis.SisyphusMonkey object at 0x7f9974256740>>, expression='Rebuild starts', disrupt_func=<bound method Nemesis.reboot_node of <sdcm.nemesis.SisyphusMonkey object at 0x7f9974256740>>, disrupt_func_kwargs={'target_node': <sdcm.cluster_azure.AzureNode object at 0x7f99745120e0>, 'hard': True, 'verify_ssh': True}, timeout=400, delay=1)]
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3832, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3334, in disrupt_rebuild_streaming_err
    self.start_and_interrupt_rebuild_streaming()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3312, in start_and_interrupt_rebuild_streaming
    ParallelObject(objects=[trigger, watcher], timeout=timeout + 60).call_objects()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 456, in call_objects
    return self.run(lambda x: x(), ignore_exceptions=ignore_exceptions)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 432, in run
    raise FuturesTimeoutError("when running on: %s" % [r.obj for r in results])
concurrent.futures._base.TimeoutError: when running on: [functools.partial(<bound method BaseNode.run_nodetool of <sdcm.cluster_azure.AzureNode object at 0x7f99745120e0>>, sub_cmd='rebuild', warning_event_on_exception=(<class 'Exception'>,), retry=0), functools.partial(<bound method Nemesis._call_disrupt_func_after_expression_logged of <sdcm.nemesis.SisyphusMonkey object at 0x7f9974256740>>, expression='Rebuild starts', disrupt_func=<bound method Nemesis.reboot_node of <sdcm.nemesis.SisyphusMonkey object at 0x7f9974256740>>, disrupt_func_kwargs={'target_node': <sdcm.cluster_azure.AzureNode object at 0x7f99745120e0>, 'hard': True, 'verify_ssh': True}, timeout=400, delay=1)]
```
Added to the issue

**Comment by fruch** [comment] 2022-12-28 16:30
@ShlomiBalalis 
I thought this is the root cause of it
https://github.com/scylladb/scylla-cluster-tests/issues/5506#issuecomment-1331832356
but I could be wrong,

**Comment by fruch** [comment] 2022-12-28 16:34
cloud be something like this 
https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/cloud-init-deployment-delay

**Comment by fruch** [comment] 2022-12-28 16:36
this nemesis has never ever passed on azure:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/b1fd2ae9b92482dad8531189e8235638

**Comment by fruch** [comment] 2022-12-28 16:37
@soyacz are you familiar with hard reboot taking so much time in azure ?

**Comment by soyacz** [comment] 2022-12-29 07:58
> @soyacz are you familiar with hard reboot taking so much time in azure ?

Not much - code for it is pretty simple:
```
    def reboot(self, name: str, wait: bool = True) -> None:
        LOGGER.info("Triggering reboot of instance: %s", name)
        task = self._azure_service.compute.virtual_machines.begin_restart(self._resource_group_name, vm_name=name)
        if wait is True:
            LOGGER.info("Waiting for reboot of instance: %s...", name)
            task.wait()
            LOGGER.info("Instance %s has been rebooted.", name)
```

I tried to dig into it / find another way but I don't see any option to make it faster - looks Azure works like this.

**Comment by fruch** [comment] 2022-12-29 08:02
> > @soyacz are you familiar with hard reboot taking so much time in azure ?
> 
> Not much - code for it is pretty simple:
> 
> ```
>     def reboot(self, name: str, wait: bool = True) -> None:
>         LOGGER.info("Triggering reboot of instance: %s", name)
>         task = self._azure_service.compute.virtual_machines.begin_restart(self._resource_group_name, vm_name=name)
>         if wait is True:
>             LOGGER.info("Waiting for reboot of instance: %s...", name)
>             task.wait()
>             LOGGER.info("Instance %s has been rebooted.", name)
> ```
> 
> I tried to dig into it / find another way but I don't see any option to make it faster - looks Azure works like this.

sounds to me there might be an issue with scylla image, did you tried it with a vanilla ubuntu image ?

**Comment by fruch** [comment] 2022-12-29 08:20
@soyacz looking at the logs again, I see the request reaches the VM 18min after we asked for it.

and seems like it's a permanent thing, please open a support ticket for azure asking them about this, maybe we should be using the poweroff api until we can sort it out ?

**Comment by soyacz** [comment] 2022-12-29 08:38
> @soyacz looking at the logs again, I see the request reaches the VM 18min after we asked for it.
> 
> and seems like it's a permanent thing, please open a support ticket for azure asking them about this, 

I can't create support ticket:
`With your Basic support plan, you can create support requests for billing, subscription management, and quota increase.`


>maybe we should be using the poweroff api until we can sort it out ?
I'm afraid with poweroff we'll lose data on ephemeral disks.

When I tried restart from Azure console some random old scylla vm (possibly without the load) it finished the process in 3 minutes.
As workaround we could try running commands on vm (like `kill -9` on scylla process and then do `reboot`)

**Comment by fruch** [comment] 2022-12-29 09:45
> > @soyacz looking at the logs again, I see the request reaches the VM 18min after we asked for it.
> > and seems like it's a permanent thing, please open a support ticket for azure asking them about this,
> 
> I can't create support ticket: `With your Basic support plan, you can create support requests for billing, subscription management, and quota increase.`
> 
> > maybe we should be using the poweroff api until we can sort it out ?
> > I'm afraid with poweroff we'll lose data on ephemeral disks.
> 
> When I tried restart from Azure console some random old scylla vm (possibly without the load) it finished the process in 3 minutes. As workaround we could try running commands on vm (like `kill -9` on scylla process and then do `reboot`)

try it from the APIs, not from the console, I'm not sure it has anything todo with load

**Comment by fruch** [comment] 2022-12-31 20:01
Seems like this is a duplicate of:
https://github.com/scylladb/scylla-cluster-tests/issues/5440

**Comment by fruch** [comment] 2023-03-20 21:14
the command line has an option `--force` that says:
```
 --force             : Force the VM to restart by redeploying it. Use if the VM is unresponsive.
```

so maybe we should redeploy as reboot  by default ?

**Comment by fruch** [comment] 2023-03-20 21:15
also in log we can clearly see Azure is seclude the reboot 15min into the future:
```
< t:2023-03-16 13:46:56,005 f:cluster_azure.py l:107  c:sdcm.cluster_azure   p:WARNING > Node longevity-10gb-3h-master-db-node-f78cd6ae-eastus-2 [13.92.183.112 | 10.0.0.6] (seed: False): Unhandled Azure scheduled event: {'EventId': 'CA9C0DC4-E841-476D-94D5-9FC2FF983BCD', 'EventStatus': 'Scheduled', 'EventType': 'Reboot', 'ResourceType': 'VirtualMachine', 'Resources': ['longevity-10gb-3h-master-db-node-eastus-2'], 'NotBefore': 'Thu, 16 Mar 2023 14:01:28 GMT', 'Description': 'Virtual machine is going to be restarted as requested by authorized user.', 'EventSource': 'User', 'DurationInSeconds': -1}
```

**Closed** 2023-03-27 06:52 UTC
Labels: Azure
