### ISSUE TITLE
raft disabled jobs still use raft

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5912] opened 2023-03-15 10:23 UTC
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Despite adding sct configuration that disables raft by adding config file: `configurations/raft/consistent_cluster_management_off.yaml`
Raft is not disabled. Downloading `scylla.yaml` file still shows `true` value for `consistent_cluster_management`. 

## Impact

We don't test what we wanted.

## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `2023.1.0~rc2-20230302.726f8a090337` with build-id `efcc950cda22875aa488c5295c6cc68f35d9cc6f`

Cluster size: 4 nodes (i3en.3xlarge)

Scylla Nodes used in this run:
- longevity-large-collections-12h-202-db-node-51dd5878-5 (54.247.7.226 | 10.4.2.162) (shards: 10)
- longevity-large-collections-12h-202-db-node-51dd5878-4 (52.213.255.32 | 10.4.0.199) (shards: 10)
- longevity-large-collections-12h-202-db-node-51dd5878-3 (18.203.172.45 | 10.4.2.74) (shards: 10)
- longevity-large-collections-12h-202-db-node-51dd5878-2 (3.250.105.3 | 10.4.1.77) (shards: 10)
- longevity-large-collections-12h-202-db-node-51dd5878-1 (54.171.138.230 | 10.4.3.121) (shards: 10)

OS / Image: `ami-0336a5a646b08dc25` (aws: eu-west-1)

Test: `longevity-large-collections-12h-test`
Test id: `51dd5878-8da1-4d87-a40d-8dd6b1f2481e`
Test name: `enterprise-2023.1/disabled_raft/longevity-large-collections-12h-test`
Test config file(s):

- [longevity-large-collections-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4ec1600f015410814cdbe6d94ce29af866d6ccda/test-cases/longevity/longevity-large-collections-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 51dd5878-8da1-4d87-a40d-8dd6b1f2481e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=51dd5878-8da1-4d87-a40d-8dd6b1f2481e)
- Show all stored logs command: `$ hydra investigate show-logs 51dd5878-8da1-4d87-a40d-8dd6b1f2481e`

## Logs:
- **db-cluster-51dd5878.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/db-cluster-51dd5878.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/db-cluster-51dd5878.tar.gz)
- **email_data-51dd5878.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/email_data-51dd5878.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/email_data-51dd5878.json.tar.gz)
- **output-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/output-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/output-51dd5878.log.tar.gz)
- **debug-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/debug-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/debug-51dd5878.log.tar.gz)
- **events-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/events-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/events-51dd5878.log.tar.gz)
- **sct-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/sct-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/sct-51dd5878.log.tar.gz)
- **normal-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/normal-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/normal-51dd5878.log.tar.gz)
- **argus-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/argus-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/argus-51dd5878.log.tar.gz)
- **raw_events-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/raw_events-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/raw_events-51dd5878.log.tar.gz)
- **critical-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/critical-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/critical-51dd5878.log.tar.gz)
- **warning-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/warning-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/warning-51dd5878.log.tar.gz)
- **summary-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/summary-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/summary-51dd5878.log.tar.gz)
- **left_processes-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/left_processes-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/left_processes-51dd5878.log.tar.gz)
- **error-51dd5878.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/error-51dd5878.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/error-51dd5878.log.tar.gz)
- **monitor-set-51dd5878.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/monitor-set-51dd5878.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/monitor-set-51dd5878.tar.gz)
- **loader-set-51dd5878.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/loader-set-51dd5878.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/51dd5878-8da1-4d87-a40d-8dd6b1f2481e/20230315_042739/loader-set-51dd5878.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/disabled_raft/job/longevity-large-collections-12h-test/2/)
</details>

**Comment by soyacz** [comment] 2023-03-15 10:25
@roydahan ^^

**Comment by roydahan** [comment] 2023-03-19 16:15
Thanks @soyacz for reporting, have you looked into the code for a root cause analysis?

@fgelcer let's make sure we mark all these tests in Argus as pending fix for this issue.

**Comment by fruch** [comment] 2023-03-23 13:46
> > Thanks @soyacz for reporting, have you looked into the code for a root cause analysis?
> > 
> 
> I looked to the code and found the root cause: https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/provision/scylla_yaml/scylla_yaml.py#L369
> So, if we update value and this is default one, we don't update - and this is a feature. We cannot blindly remove this behavior as we use it in the code. In code we update `ScyllaYaml` object partially in steps, so next step could remove previous ones settings. This causes problem, we never can go back to defaults.
> 
> Quick fix would be to set `consistent_cluster_management` default to `True` but from the other side it will cause problems for non-ami tests where we don't set this setting.
> For other fixes I'd need to think more - before that I need your opinion.
> Maybe @fruch have some insight into this?

The default should be True as in Scylla master and 5.2

And we can try remove that check, I'm not sure why we want to remove values which are set as default, sounds harmless to remove it, or I'm missing something.

Anyhow we have good enough unittests for verifying it's behavior

**Comment by soyacz** [comment] 2023-03-23 13:56
> The default should be True as in Scylla master and 5.2
> 

If it's default, we should change default in `ScyllaYaml` - thus fixing this issue.

> And we can try remove that check, I'm not sure why we want to remove values which are set as default, sounds harmless to remove it, or I'm missing something.
> 
> Anyhow we have good enough unittests for verifying it's behavior

That was my first try, but found unittests failing - and showing this is a valid feature.

**Comment by soyacz** [comment] 2023-03-23 13:57
* valid feature - I meant, that otherwise might not work as expected. I don't think it's good behavior, but changing it would require `ScyllaYaml` redesign.

**Comment by fruch** [comment] 2023-03-23 14:03
> * valid feature - I meant, that otherwise might not work as expected. I don't think it's good behavior, but changing it would require `ScyllaYaml` redesign.

Don't know if redesign, just removing on feature that isn't intuitive what so ever.

code should do what we ask of it, and not silently drop things.

recently we addressed one such "feature" that caused default scylla yaml not to pass unknown values.
again unexpected silent safeguard that we don't need.

**Comment by roydahan** [comment] 2023-03-27 20:59
consistent_cluster_management default is True starting 5.2.
This is relevant only for fresh installs, so we need to make sure that when testing rolling upgrades, we don't set it by default to True.
(There are specific tests for this variant).

**Comment by roydahan** [comment] 2023-03-27 22:36
I agree.

**Closed** 2023-03-30 10:50 UTC
