### ISSUE TITLE
Data differs after upgrade running on the Centos8

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#4678] opened 2022-04-22 09:43 UTC
## Installation details

Kernel Version: 4.18.0-373.el8.x86_64
Base Scylla version: `5.0.rc3-20220406.f92622e0d` with build-id `2b79c4744216b294fdbd2f277940044c899156ea`
Target Scylla version: `5.1.dev-0.20220415.75786c42cb2e` with build-id `624bf766a24fba740b118c805912a1b94df59dc5`
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-master-centos-8-db-node-bc6b7ad9-0-4 (34.148.25.116 | 10.142.0.92) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-bc6b7ad9-0-3 (34.148.208.214 | 10.142.0.76) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-bc6b7ad9-0-2 (34.139.249.57 | 10.142.0.57) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-bc6b7ad9-0-1 (34.148.206.189 | 10.142.0.51) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: eu-west-1)

Test: `rolling-upgrade-centos8-test`
Test id: `bc6b7ad9-52fb-498e-942b-80c43f5c39f3`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-centos8-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1db1271a4a1de09f1d87b1f43e367e8cedca2af1/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

Here are the steps of the test:
1) Upgrade one node
2) Upgrade one more node
3) Rollback (2)
4) Upgrade all other nodes
5) Check data

So, after the upgrade of all the nodes we got the diff in data:

```
> SELECT * FROM dense_cf_test 
        WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 
        AND ip = '192.168.0.3' 

...

> Traceback (most recent call last):                                                                   
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3253, in _run_db_queries       
>     self.assertEqual([list(row) for row in res], item['results'][i])                                 
>   File "/usr/local/lib/python3.10/unittest/case.py", line 837, in assertEqual                        
>     assertion_func(first, second, msg=msg)                                                           
>   File "/usr/local/lib/python3.10/unittest/case.py", line 1043, in assertListEqual                   
>     self.assertSequenceEqual(list1, list2, msg, seq_type=list)                                       
>   File "/usr/local/lib/python3.10/unittest/case.py", line 1025, in assertSequenceEqual               
>     self.fail(msg)                                                                                   
>   File "/usr/local/lib/python3.10/unittest/case.py", line 667, in fail                               
>     raise self.failureException(msg)                                                                 
> AssertionError: Lists differ: [[UUID('f47ac10b-58cc-4372-a567-0e02b2c3d479'), '192.168.0.3', None, 42]] != []
>                                                                                                      
> First list contains 1 additional elements.                                                           
> First extra element 0:                                                                               
> [UUID('f47ac10b-58cc-4372-a567-0e02b2c3d479'), '192.168.0.3', None, 42]                              
>                                                                                                      
> - [[UUID('f47ac10b-58cc-4372-a567-0e02b2c3d479'), '192.168.0.3', None, 42]]                          
> + []
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor bc6b7ad9-52fb-498e-942b-80c43f5c39f3`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=bc6b7ad9-52fb-498e-942b-80c43f5c39f3)
- Show all stored logs command: `$ hydra investigate show-logs bc6b7ad9-52fb-498e-942b-80c43f5c39f3`

## Logs:
- **db-cluster-bc6b7ad9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bc6b7ad9-52fb-498e-942b-80c43f5c39f3/20220416_095734/db-cluster-bc6b7ad9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bc6b7ad9-52fb-498e-942b-80c43f5c39f3/20220416_095734/db-cluster-bc6b7ad9.tar.gz)
- **monitor-set-bc6b7ad9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bc6b7ad9-52fb-498e-942b-80c43f5c39f3/20220416_095734/monitor-set-bc6b7ad9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bc6b7ad9-52fb-498e-942b-80c43f5c39f3/20220416_095734/monitor-set-bc6b7ad9.tar.gz)
- **loader-set-bc6b7ad9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bc6b7ad9-52fb-498e-942b-80c43f5c39f3/20220416_095734/loader-set-bc6b7ad9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bc6b7ad9-52fb-498e-942b-80c43f5c39f3/20220416_095734/loader-set-bc6b7ad9.tar.gz)
- **sct-runner-bc6b7ad9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bc6b7ad9-52fb-498e-942b-80c43f5c39f3/20220416_095734/sct-runner-bc6b7ad9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bc6b7ad9-52fb-498e-942b-80c43f5c39f3/20220416_095734/sct-runner-bc6b7ad9.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos8-test/130/)

**Comment by roydahan** [comment] 2022-05-03 00:33
This issue should be investigated properly first.

**Comment by ShlomiBalalis** [comment] 2022-05-10 11:43
In my scenario, the cause of the error seem to be that some of a line not being deleted.
First, we insert the following:
```
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (0, 0, 0, 0, 0)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (0, 0, 1, 1, 1)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (0, 1, 0, 2, 2)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (0, 1, 1, 3, 3)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (1, 0, 0, 4, 4)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (1, 0, 1, 5, 5)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (1, 1, 0, 6, 6)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (1, 1, 1, 7, 7)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (2, 0, 0, 8, 8)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (2, 0, 1, 9, 9)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (2, 1, 0, 10, 10)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (2, 1, 1, 11, 11)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (3, 0, 0, 12, 12)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (3, 0, 1, 13, 13)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (3, 1, 0, 14, 14)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (3, 1, 1, 15, 15)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (4, 0, 0, 16, 16)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (4, 0, 1, 17, 17)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (4, 1, 0, 18, 18)
INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (4, 1, 1, 19, 19)
```
Afterwards, we check the data in the table, and then we delete all of the rows where `c1 = 0`:
```
DELETE FROM range_tombstones_test WHERE k = 0 AND c1 = 0
DELETE FROM range_tombstones_test WHERE k = 1 AND c1 = 0
DELETE FROM range_tombstones_test WHERE k = 2 AND c1 = 0
DELETE FROM range_tombstones_test WHERE k = 3 AND c1 = 0
DELETE FROM range_tombstones_test WHERE k = 4 AND c1 = 0
```
Then we check the table again, one key at the time:
```
SELECT v1, v2 FROM range_tombstones_test WHERE k = 0
SELECT v1, v2 FROM range_tombstones_test WHERE k = 1
SELECT v1, v2 FROM range_tombstones_test WHERE k = 2
SELECT v1, v2 FROM range_tombstones_test WHERE k = 3
SELECT v1, v2 FROM range_tombstones_test WHERE k = 4
```
The last key, `k = 4` is the problematic one.
Since we deleted the entirety of `c1 = 0', we expect only `(4, 1, 0, 18, 18)` and `(4, 1, 1, 19, 19)` to remain, but instead we discover that `(4, 0, 1, 17, 17)` was not deleted as it should have and remained in the table.

**Comment by fgelcer** [comment] 2022-05-10 12:38
@ShlomiBalalis , did any of the `DELETE` queries return errors or exceptions?

**Comment by ShlomiBalalis** [comment] 2022-05-10 13:31
> @ShlomiBalalis , did any of the `DELETE` queries return errors or exceptions?

They did not, no.

**Comment by avikivity** [comment] 2022-05-10 14:34
What consistency level is used? with QUORUM, the race will be avoided.

**Comment by fruch** [comment] 2022-05-10 14:36
> so it sounds to be a race condition (and you are deleting and reading too fast, before the delete command was replicated) that could be caused a an issue in Scylla.

this test is exactly for test this, and it's there for a long long time:
https://github.com/scylladb/scylla-cluster-tests/commit/24c76e5ba6a997b5b2fc307ec1507bfe4cac00c7

**Comment by ShlomiBalalis** [comment] 2022-05-10 14:39
> What consistency level is used? with QUORUM, the race will be avoided.

It's [quorum](https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/fill_db_data.py#L3361)

**Comment by avikivity** [comment] 2022-05-10 16:39
Then it can't be a race.

**Comment by ShlomiBalalis** [comment] 2022-05-11 10:15
@vponomaryov's original error was recreated identically in the ubuntu-20 rolling upgrade of master:
## Installation details

Kernel Version: 5.13.0-1024-gcp
Scylla version (or git commit hash): `5.0~rc3-20220406.f92622e0d` with build-id `2b79c4744216b294fdbd2f277940044c899156ea`
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-master-ubuntu-focal-db-node-90a273d1-0-4 (34.139.203.20 | 10.142.0.136) (shards: 8)
- rolling-upgrade-master-ubuntu-focal-db-node-90a273d1-0-3 (34.148.168.168 | 10.142.0.130) (shards: 8)
- rolling-upgrade-master-ubuntu-focal-db-node-90a273d1-0-2 (34.148.254.254 | 10.142.0.125) (shards: 8)
- rolling-upgrade-master-ubuntu-focal-db-node-90a273d1-0-1 (34.148.6.63 | 10.142.0.120) (shards: 8)


OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts` (gce: us-east1)

Test: `rolling-upgrade-ubuntu20.04-test`
Test id: `90a273d1-08c1-40a3-a14d-7337f78857b5`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ubuntu20.04-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ea4aaa1b4f8b631fea2df71d8206e815c3d7614d/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

After the upgrade of the last node, when trying to verify the data, we run into the same failure:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3253, in _run_db_queries
    self.assertEqual([list(row) for row in res], item['results'][i])
  File "/usr/local/lib/python3.10/unittest/case.py", line 837, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python3.10/unittest/case.py", line 1043, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/lib/python3.10/unittest/case.py", line 1025, in assertSequenceEqual
    self.fail(msg)
  File "/usr/local/lib/python3.10/unittest/case.py", line 667, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: [[UUID('f47ac10b-58cc-4372-a567-0e02b2c3d479'), '192.168.0.3', None, 42]] != []

First list contains 1 additional elements.
First extra element 0:
[UUID('f47ac10b-58cc-4372-a567-0e02b2c3d479'), '192.168.0.3', None, 42]

- [[UUID('f47ac10b-58cc-4372-a567-0e02b2c3d479'), '192.168.0.3', None, 42]]
+ []
```
This seems to be another result of a line that was not deleted properly:
First, before the upgrade of the node, we insert (and update) data of the `dense_cf_test` table:
```
CREATE TABLE dense_cf_test (
userid uuid,
ip text,
port int,
time bigint,
PRIMARY KEY (userid, ip, port)
) WITH COMPACT STORAGE
AND compaction = {'class': 'DateTieredCompactionStrategy'}
```
Among other insertions, we insert the following line:
`INSERT INTO dense_cf_test (userid, ip, time) VALUES (f47ac10b-58cc-4372-a567-0e02b2c3d479, '192.168.0.3', 42)`
After the node was upgraded, we execute the following:
`DELETE FROM dense_cf_test WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 AND ip = '192.168.0.3'`
And as such, we expect the line to be deleted from the table. But when we select it, it's still there.

It's important to note that the same process of inserts, deletions and verifacations occur with each node upgrade. The failure only appeared after the upgrade of the last remaining node (node 3)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 90a273d1-08c1-40a3-a14d-7337f78857b5`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=90a273d1-08c1-40a3-a14d-7337f78857b5)
- Show all stored logs command: `$ hydra investigate show-logs 90a273d1-08c1-40a3-a14d-7337f78857b5`

## Logs:
- **db-cluster-90a273d1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/90a273d1-08c1-40a3-a14d-7337f78857b5/20220507_084831/db-cluster-90a273d1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/90a273d1-08c1-40a3-a14d-7337f78857b5/20220507_084831/db-cluster-90a273d1.tar.gz)
- **monitor-set-90a273d1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/90a273d1-08c1-40a3-a14d-7337f78857b5/20220507_084831/monitor-set-90a273d1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/90a273d1-08c1-40a3-a14d-7337f78857b5/20220507_084831/monitor-set-90a273d1.tar.gz)
- **loader-set-90a273d1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/90a273d1-08c1-40a3-a14d-7337f78857b5/20220507_084831/loader-set-90a273d1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/90a273d1-08c1-40a3-a14d-7337f78857b5/20220507_084831/loader-set-90a273d1.tar.gz)
- **sct-runner-90a273d1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/90a273d1-08c1-40a3-a14d-7337f78857b5/20220507_084831/sct-runner-90a273d1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/90a273d1-08c1-40a3-a14d-7337f78857b5/20220507_084831/sct-runner-90a273d1.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ubuntu20.04-test/66/)

**Comment by roydahan** [comment] 2022-05-11 20:33
I think that there should be idetical code in dtest that test the same scenario.
@ShlomiBalalis please verify it passes and please verify that it's the exact same code and nothing was changed in dtest to make it pass.

**Comment by roydahan** [comment] 2022-05-11 20:50
So, I partially did it my self:

This is the code in dtest (thanks to the pytest migration its history on master is a lie):
```
   def range_tombstones_test(self):
        """ Test deletion by 'composite prefix' (range tombstones) """
        cluster = self.cluster

        # Uses 3 nodes just to make sure RowMutation are correctly serialized
        cluster.populate(3).start()
        node1 = cluster.nodelist()[0]
        time.sleep(0.2)

        session = self.patient_cql_connection(node1)
        create_ks(session, 'ks', 1)

        session.execute("""
            CREATE TABLE test1 (
                k int,
                c1 int,
                c2 int,
                v1 int,
                v2 int,
                PRIMARY KEY (k, c1, c2)
            );
        """)
        time.sleep(1)

        rows = 5
        col1 = 2
        col2 = 2
        cpr = col1 * col2
        for i in range(0, rows):
            for j in range(0, col1):
                for k in range(0, col2):
                    n = (i * cpr) + (j * col2) + k
                    session.execute("INSERT INTO test1 (k, c1, c2, v1, v2) VALUES (%d, %d, %d, %d, %d)" %
                                    (i, j, k, n, n))

        for i in range(0, rows):
            res = session.execute("SELECT v1, v2 FROM test1 where k = %d" % i)
            assert rows_to_list(res) == [[x, x] for x in range(i * cpr, (i + 1) * cpr)], list(res)

        for i in range(0, rows):
            session.execute("DELETE FROM test1 WHERE k = %d AND c1 = 0" % i)

        for i in range(0, rows):
            res = session.execute("SELECT v1, v2 FROM test1 WHERE k = %d" % i)
            assert rows_to_list(res) == [[x, x] for x in range(i * cpr + col1, (i + 1) * cpr)], list(res)

        cluster.flush()
        time.sleep(0.2)

        for i in range(0, rows):
            res = session.execute("SELECT v1, v2 FROM test1 WHERE k = %d" % i)
            assert rows_to_list(res) == [[x, x] for x in range(i * cpr + col1, (i + 1) * cpr)], list(res)

```
And it's passing consistently on master.
We can maybe try to reproduce in dtest with the upgrade tests and much limited scenario (just calling this test) at the relevant times of the upgrade process.

**Comment by ilya-rarov** [comment] 2023-06-15 15:42
Looks like the error from Slomo's comment https://github.com/scylladb/scylla-cluster-tests/issues/4678#issuecomment-1115498035 was reproduced

## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

Inserting data into `range_tombstones_test`
```
< t:2023-06-05 22:49:41,628 f:common.py       l:1488 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (0, 0, 0, 0, 0)' ...
< t:2023-06-05 22:49:41,631 f:common.py       l:1488 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (0, 0, 1, 1, 1)' ...
< t:2023-06-05 22:49:41,633 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (0, 1, 0, 2, 2)' ...
< t:2023-06-05 22:49:41,636 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (0, 1, 1, 3, 3)' ...
< t:2023-06-05 22:49:41,638 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (1, 0, 0, 4, 4)' ...
< t:2023-06-05 22:49:41,641 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (1, 0, 1, 5, 5)' ...
< t:2023-06-05 22:49:41,644 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (1, 1, 0, 6, 6)' ...
< t:2023-06-05 22:49:41,646 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (1, 1, 1, 7, 7)' ...
< t:2023-06-05 22:49:41,648 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (2, 0, 0, 8, 8)' ...
< t:2023-06-05 22:49:41,650 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (2, 0, 1, 9, 9)' ...
< t:2023-06-05 22:49:41,652 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (2, 1, 0, 10, 10)' ...
< t:2023-06-05 22:49:41,654 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (2, 1, 1, 11, 11)' ...
< t:2023-06-05 22:49:41,657 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (3, 0, 0, 12, 12)' ...
< t:2023-06-05 22:49:41,659 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (3, 0, 1, 13, 13)' ...
< t:2023-06-05 22:49:41,661 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (3, 1, 0, 14, 14)' ...
< t:2023-06-05 22:49:41,662 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (3, 1, 1, 15, 15)' ...
< t:2023-06-05 22:49:41,664 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (4, 0, 0, 16, 16)' ...
< t:2023-06-05 22:49:41,666 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (4, 0, 1, 17, 17)' ...
< t:2023-06-05 22:49:41,668 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (4, 1, 0, 18, 18)' ...
< t:2023-06-05 22:49:41,670 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (4, 1, 1, 19, 19)' ...
```
Deleting rows where `c1 = 0`
```
< t:2023-06-05 23:00:47,554 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'DELETE FROM range_tombstones_test WHERE k = 0 AND c1 = 0' ...
< t:2023-06-05 23:00:47,588 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'DELETE FROM range_tombstones_test WHERE k = 1 AND c1 = 0' ...
< t:2023-06-05 23:00:47,590 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'DELETE FROM range_tombstones_test WHERE k = 2 AND c1 = 0' ...
< t:2023-06-05 23:00:47,592 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'DELETE FROM range_tombstones_test WHERE k = 3 AND c1 = 0' ...
< t:2023-06-05 23:00:47,597 f:common.py       l:1488 c:utils                p:DEBUG > Executing CQL 'DELETE FROM range_tombstones_test WHERE k = 4 AND c1 = 0' ...
```
Verifying the data
```
< t:2023-06-05 23:00:47,598 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'SELECT v1, v2 FROM range_tombstones_test WHERE k = 0' ...
< t:2023-06-05 23:00:47,600 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'SELECT v1, v2 FROM range_tombstones_test WHERE k = 1' ...
< t:2023-06-05 23:00:47,603 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'SELECT v1, v2 FROM range_tombstones_test WHERE k = 2' ...
< t:2023-06-05 23:00:47,605 f:common.py       l:1480 c:utils                p:DEBUG > Executing CQL 'SELECT v1, v2 FROM range_tombstones_test WHERE k = 3' ...
```
The problematic key was 3
```
< t:2023-06-05 23:00:47,609 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > SELECT v1, v2 FROM range_tombstones_test WHERE k = 3 
```
The row with `v1 = 13` and `v2 = 13` was expected to be deleted but appeared in the result 
```
2023-06-05 23:01:04.580: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=6d553c41-c8c1-4464-9a7c-d1b955310942, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 660, in test_rolling_upgrade
    self.fill_and_verify_db_data('after upgraded %s' % self.db_cluster.node_to_upgrade.name)
  File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 471, in fill_and_verify_db_data
    self.verify_db_data()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3365, in verify_db_data
    self.run_db_queries(session, session.default_fetch_size)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3296, in run_db_queries
    self._run_db_queries(item, session)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3256, in _run_db_queries
    raise ex
  File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3253, in _run_db_queries
    self.assertEqual([list(row) for row in res], item['results'][i])
AssertionError: Lists differ: [[13, 13], [14, 14], [15, 15]] != [[14, 14], [15, 15]]

First differing element 0:
[13, 13]
[14, 14]

First list contains 1 additional elements.
First extra element 2:
[15, 15]

- [[13, 13], [14, 14], [15, 15]]
?  ----------

+ [[14, 14], [15, 15]]
```

## How frequently does it reproduce?

On rare occasions

## Installation details

Kernel Version: 5.15.0-1034-aws
Scylla version (or git commit hash): `5.0.13-20230423.a0ca8abe4` with build-id `1196f46d1be44927c95ac67703df3ab2ef98a332`




Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--null-db-node-38946836-4 (54.75.55.175 | 10.4.0.101) (shards: 8)
- rolling-upgrade--null-db-node-38946836-3 (34.243.251.45 | 10.4.1.4) (shards: 8)
- rolling-upgrade--null-db-node-38946836-2 (52.214.85.3 | 10.4.3.5) (shards: 8)
- rolling-upgrade--null-db-node-38946836-1 (54.154.51.245 | 10.4.1.19) (shards: 8)


OS / Image: `ami-0a5b4324be630104d` (aws: eu-west-1)

Test: `rolling-upgrade-ami-test`
Test id: `38946836-93d3-46ef-918e-a9e3a8b079c2`
Test name: `scylla-5.1/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/022f75b3777727838aa9f1eca7b91ee4a576c4f7/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 38946836-93d3-46ef-918e-a9e3a8b079c2`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=38946836-93d3-46ef-918e-a9e3a8b079c2)
- Show all stored logs command: `$ hydra investigate show-logs 38946836-93d3-46ef-918e-a9e3a8b079c2`


## Logs:
- **db-cluster-38946836.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/38946836-93d3-46ef-918e-a9e3a8b079c2/20230605_231140/db-cluster-38946836.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/38946836-93d3-46ef-918e-a9e3a8b079c2/20230605_231140/db-cluster-38946836.tar.gz)
- **monitor-set-38946836.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/38946836-93d3-46ef-918e-a9e3a8b079c2/20230605_231140/monitor-set-38946836.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/38946836-93d3-46ef-918e-a9e3a8b079c2/20230605_231140/monitor-set-38946836.tar.gz)
- **loader-set-38946836.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/38946836-93d3-46ef-918e-a9e3a8b079c2/20230605_231140/loader-set-38946836.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/38946836-93d3-46ef-918e-a9e3a8b079c2/20230605_231140/loader-set-38946836.tar.gz)
- **sct-runner-38946836.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/38946836-93d3-46ef-918e-a9e3a8b079c2/20230605_231140/sct-runner-38946836.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/38946836-93d3-46ef-918e-a9e3a8b079c2/20230605_231140/sct-runner-38946836.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.1/job/rolling-upgrade/job/rolling-upgrade-ami-test/52/)
[Argus](https://argus.scylladb.com/test/2a24f9ef-bb22-436b-926f-4f7e506f1c61/runs?additionalRuns[]=38946836-93d3-46ef-918e-a9e3a8b079c2)
</details>

**Comment by roydahan** [comment] 2023-06-18 14:18
@ilya-rarov you need to check if the deletion that should have happened, happened successfully or failed.
I recall taht @aleksbykov saw somehing similar in the past that the deletions failed and this failed the verification afterwards.

If the deletion didn't fail, it's a real issue in Scylla, else it's an issue with the test that we need to catch earlier (and also understand why the deletion failed - which may indicate on another issue).

**Comment by ilya-rarov** [comment] 2023-06-28 07:36
@roydahan in `sct.log` it looks like all the `DELETE` operations succeeded (I don't see any errors or exceptions there).
I also looked into node logs, but I could not recognize any trace of deletion operation there.
Does Scylla show any signs of ongoing deletion in the logs?

**Comment by fgelcer** [comment] 2023-06-28 07:45
perhaps @ShlomiBalalis and @Mark-Gurevich are seeing same issue...

**Comment by roydahan** [comment] 2023-06-28 14:53
1. @ilya-rarov please do not let such issues to wait for that long.
2. As I mentioned above, I think that @aleksbykov investigated such an issue, so please contact him directly and ask him to help you with it.

**Comment by ilya-rarov** [comment] 2023-07-04 10:12
After a discussion with Alex tried to reproduce the problem with tracing enabled for the queries to get more information from Scylla.
The first try (build [rolling-upgrade-ami-test-ilya/2/](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/ilya/job/SCT/job/rolling-upgrade-ami-test-ilya/2/)) was unsuccessful - the problem was not reproduced

**Comment by fruch** [comment] 2024-09-22 10:19
@roydahan 

I don't think we seen those issue in quite some time...
if it gonna happen again it should be reported to scylla core (and supplying proper information)

meanwhile closing this one.

**Closed by fruch** 2024-09-22 10:19 UTC
